/* Motor de las apps de rutina WGYMADNSPORT (ingreso, cronómetro, series,
   progreso, peso, récords, compartir). El contenido de cada rutina va en
   rutinas/<nombre>.json; la página lo indica con data-rutina. */
"use strict";
const DEMO=false;
/* La rutina (días, ejercicios, fotos) vive en rutinas/<nombre>.json; este
   archivo es solo la app. Si el archivo no llega o viene incompleto, se usa
   la última versión buena guardada en este celular. */
const RUTINA_URL=document.currentScript.dataset.rutina;
let RUTINA=null,PLAN=[];
function cargarRutina(){
 const cacheKey="wgym_rutina_cache_"+RUTINA_URL;
 const usar=r=>{RUTINA=r;PLAN=r.dias;return r};
 const guardada=()=>{try{const r=JSON.parse(localStorage.getItem(cacheKey));if(r&&!validarRutina(r).length)return usar(r)}catch{}throw Error("Sin rutina")};
 return fetch(RUTINA_URL,{cache:"no-cache"}).then(r=>{if(!r.ok)throw Error("HTTP "+r.status);return r.json()}).then(r=>{const errores=validarRutina(r);if(errores.length){console.warn("Rutina con problemas:",errores);return guardada()}try{localStorage.setItem(cacheKey,JSON.stringify(r))}catch{}return usar(r)}).catch(()=>guardada());
}
const rutinaLista=cargarRutina();
const nDias=()=>PLAN.length;
/* Opciones de cada rutina (en su JSON, todas opcionales):
   visual: "pares" (fotos inicio/final, por defecto) · "imagen" (una foto) · "video"
   cardio: "elegir" (elige bicicleta/remadora/trotadora, por defecto) · "texto"
           (texto de cierre del día, con video opcional en cooldownVideo)
   cardioTitulo: título por defecto del cierre cuando cardio es "texto"
   diasSemana: día de la semana de cada sesión (0 = lunes), ej. [0,2,4]
   letrasDia: letras del día en la grilla semanal (por defecto 3)
   nombreTam: tamaño del nombre en la tarjeta para compartir (por defecto 48) */
const opt=(k,def)=>RUTINA&&RUTINA[k]!=null?RUTINA[k]:def;
const nSeries=(di,ei)=>{const x=PLAN[di].exercises[ei];return Math.max(1,Number(x.series)||parseInt(x.sets,10)||3)};
(function(){
 var el = document.getElementById("dateBar");
 if(el){
  var d = new Date();
  var s = d.toLocaleDateString("es-CL", { weekday:"long", day:"numeric", month:"long" });
  el.textContent = s.charAt(0).toUpperCase() + s.slice(1);
 }
})();
const $=id=>document.getElementById(id);
let currentDay=0,currentEx=0,memberName=DEMO?"VISTA PREVIA":"",memberFv=null,memberFirst="",welcomeTimer=null,countdown=null,audioCtx=null,shareBlob=null;
const key=()=>RUTINA.claveProgreso+memberName.toLowerCase().replace(/[^a-záéíóúñ ]/gi,"").trim();
let progress={version:2,weeks:{}};
function chileDate(){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=t=>+parts.find(x=>x.type===t).value;return new Date(Date.UTC(get("year"),get("month")-1,get("day")))}
function weekKey(){const d=chileDate(),weekday=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-weekday);return d.toISOString().slice(0,10)}
function thisWeek(){const k=weekKey();return progress.weeks[k]||(progress.weeks[k]={sets:{},days:{}})}
function load(){let old={};try{old=JSON.parse(localStorage.getItem(key()))||{}}catch{}if(old.version===2&&old.weeks){progress=old;return}progress={version:2,weeks:{}};const entries=Object.entries(old).filter(([k])=>/^\d+_\d+_\d+$/.test(k));if(entries.length){thisWeek().sets=Object.fromEntries(entries);save()}}
function save(){try{localStorage.setItem(key(),JSON.stringify(progress))}catch{}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function norm(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z ]/g,"").replace(/\s+/g," ").trim()}
function expired(serial){const d=new Date(Date.UTC(1899,11,30)+Number(serial)*86400000);const now=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Santiago",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());return d.toISOString().slice(0,10)<now}
function fechaSerialUTC(serial){return new Date(Date.UTC(1899,11,30)+Number(serial)*86400000)}
function fechaDMY(serial){const d=fechaSerialUTC(serial);return String(d.getUTCDate()).padStart(2,"0")+"-"+String(d.getUTCMonth()+1).padStart(2,"0")+"-"+d.getUTCFullYear()}
function diasParaVencer(serial){return Math.round((fechaSerialUTC(serial)-chileDate())/86400000)}
function pintarVencimiento(serial){const el=$("noticeBar");if(!el||serial==null)return;const d=diasParaVencer(serial),venc=fechaDMY(serial);if(d<0){el.dataset.v="bad";el.textContent="\u{1F534} Tu membres\u00eda venci\u00f3 el "+venc+" \u00b7 hace "+Math.abs(d)+(Math.abs(d)===1?" d\u00eda":" d\u00edas")+". Pasa a renovar en recepci\u00f3n."}else if(d===0){el.dataset.v="warn";el.textContent="\u26A0\uFE0F Tu membres\u00eda vence hoy ("+venc+"). Acu\u00e9rdate de renovar."}else if(d<=1){el.dataset.v="warn";el.textContent="\u26A0\uFE0F Vence el "+venc+" \u00b7 queda 1 d\u00eda. Acu\u00e9rdate de renovar."}else{el.dataset.v="ok";el.textContent="\u2705 Vence el "+venc+" \u00b7 quedan "+d+" d\u00edas."}}
async function login(){const name=norm($("member").value);if(!name||name.split(" ").length<2){$("error").textContent="Escribe nombre y apellido.";return}
 try{await rutinaLista}catch{$("error").textContent="No se pudo cargar la rutina. Revisa tu conexión a internet e intenta de nuevo.";return}
 try{const c=new AbortController();const t=setTimeout(()=>c.abort(),4000);const r=await fetch("socios.json?v="+Date.now(),{cache:"no-store",signal:c.signal});clearTimeout(t);if(!r.ok)throw Error();const j=await r.json();const members=Array.isArray(j)?j:(j.socios||[]);const m=members.find(x=>norm(x.n+" "+x.a)===name||norm(x.a+" "+x.n)===name);
 if(!m){$("error").textContent="No encontramos tu nombre en la lista de socios.";return}if(expired(m.fv)){$("error").textContent="Tu plan aparece vencido. Consulta en recepción.";return}memberFv=m.fv;memberName=norm(m.n+" "+m.a);memberFirst=(m.n||"").trim();mostrarBienvenida();}
 catch{$("error").textContent="No se pudo consultar la lista. Intenta de nuevo o pregunta en recepción."}}
function start(){load();const wd=(chileDate().getUTCDay()+6)%7;const dS=opt("diasSemana",null);currentDay=dS?dS.reduce((best,w,i)=>w<=wd?i:best,0):Math.min(nDias()-1,wd);if($("totalDias"))$("totalDias").textContent=String(nDias()).padStart(2,"0");$("login").hidden=true;$("app").hidden=false;$("userpill").textContent=memberName;render();renderWeight();pintarVencimiento(memberFv)}
function mostrarBienvenida(){const el=$("welcome");if(!el){start();return}const wl=$("welcomeLogo");if(wl&&!wl.src){const hdr=document.querySelector(".top img");if(hdr)wl.src=hdr.src}$("welcomeName").textContent="¡Hola, "+(memberFirst||"")+"!";el.hidden=false;requestAnimationFrame(()=>el.classList.add("open"));welcomeTimer=setTimeout(()=>{el.classList.remove("open");el.hidden=true;start()},25000)}
function saltarBienvenida(){clearTimeout(welcomeTimer);const el=$("welcome");if(!el){start();return}el.classList.remove("open");el.hidden=true;start()}
function prevWeekKey(){const d=new Date(weekKey()+"T00:00:00Z");d.setUTCDate(d.getUTCDate()-7);return d.toISOString().slice(0,10)}
function semanaAnteriorCompletados(){const w=progress.weeks[prevWeekKey()];if(!w)return null;return PLAN.reduce((n,_,i)=>n+(w.days[i]?.done?1:0),0)}
function bestFor(di,ei){const name=PLAN[di].exercises[ei].name,isPlank=norm(name)==="PLANCHA FRONTAL";let best=0;for(const w of Object.values(progress.weeks)){for(let i=0;i<nSeries(di,ei);i++){const s=w.sets?.[di+"_"+ei+"_"+i];if(s?.done){const value=Number(isPlank?s.reps:s.kg);if(Number.isFinite(value))best=Math.max(best,value)}}}return best?best+(isPlank?" seg":" kg"):"Sin registro"}
function streakCount(){let monday=new Date(weekKey()+"T00:00:00Z"),count=0;const complete=k=>Array.from({length:nDias()},(_,i)=>progress.weeks[k]?.days?.[i]?.done).every(Boolean);if(!complete(weekKey()))monday.setUTCDate(monday.getUTCDate()-7);for(let i=0;i<520;i++){const k=monday.toISOString().slice(0,10);if(!complete(k))break;count++;monday.setUTCDate(monday.getUTCDate()-7)}return count}
function renderDashboard(){const w=thisWeek(),completed=PLAN.reduce((n,_,i)=>n+(w.days[i]?.done?1:0),0);$("weekLabel").textContent="DESDE "+weekKey().split("-").reverse().join("/");const N=nDias();$("progressFill").style.width=completed*100/N+"%";$("progressbar").setAttribute("aria-valuemax",N);$("progressbar").setAttribute("aria-valuenow",completed);$("progressText").textContent=completed+" DE "+N+" ENTRENAMIENTOS COMPLETADOS";$("weeklyMedal").hidden=completed!==N;$("weeklyMedal").innerHTML='<span aria-hidden="true">🏅</span> ¡SEMANA COMPLETADA!<br>'+N+" DE "+N+" ENTRENAMIENTOS";$("weekGrid").style.gridTemplateColumns="repeat("+N+",1fr)";$("weekGrid").innerHTML=PLAN.map((d,i)=>`<div class="week-cell ${w.days[i]?.done?"done":""} ${i===currentDay?"active":""}">${esc(d.weekday.slice(0,opt("letrasDia",3)).toUpperCase())}<b>${w.days[i]?.done?"✓":String(i+1).padStart(2,"0")}</b></div>`).join("");
 const streak=streakCount();$("streakTitle").textContent=streak?streak+" "+(streak===1?"SEMANA SEGUIDA":"SEMANAS SEGUIDAS"):"TU RACHA COMIENZA AQUÍ";$("streakDetail").textContent=streak?completed===N?"¡Semana completa! Tu constancia sigue creciendo.":"Completa esta semana para mantener tu racha.":"Completa los "+N+" días para encender tu primera semana.";
const prevCompleted=semanaAnteriorCompletados();const wc=$("weekCompare");if(wc){if(prevCompleted==null){wc.hidden=true}else{const diff=completed-prevCompleted;const arrow=diff>0?"▲":(diff<0?"▼":"■");const msg=diff>0?"Vas mejor que la semana pasada":(diff<0?"La semana pasada llevabas más":"Igual que la semana pasada");wc.hidden=false;wc.innerHTML="<b>"+arrow+" "+completed+"/"+N+"</b> esta semana · <b>"+prevCompleted+"/"+N+"</b> la semana pasada — "+msg}}
 const records=PLAN.flatMap((d,di)=>d.exercises.map((x,ei)=>({name:x.name,best:bestFor(di,ei)}))).filter(x=>x.best!=="Sin registro");$("recordPanel").innerHTML="<h3>Mis mejores marcas</h3>"+(records.length?records.map(x=>`<p>${esc(x.name)} · <b>${esc(x.best)}</b></p>`).join(""):"<p>Marca una serie con peso o tiempo para ver tus récords aquí.</p>");
 const previous=Object.entries(progress.weeks).filter(([k])=>k!==weekKey()).sort(([a],[b])=>b.localeCompare(a));$("historyPanel").innerHTML="<h3>Semanas anteriores</h3>"+(previous.length?previous.map(([k,v])=>{const done=Object.values(v.days||{}).filter(x=>x.done).length;return `<p>${done===N?"🏅 ":""}Semana del ${esc(k.split("-").reverse().join("/"))} · <b>${done}/${N} días</b> · ${Object.values(v.sets||{}).filter(x=>x.done).length} series</p>`}).join(""):"<p>Tu primera semana está en marcha. Aquí aparecerán las anteriores.</p>")}
function clockState(){progress.clocks ||= {};const k=weekKey();progress.clocks[k] ||= {};return progress.clocks[k][currentDay] ||= {elapsed:0,startedAt:null,running:false,ended:false}}
function clockElapsed(c){return Math.max(0,c.elapsed+(c.running?Math.max(0,Date.now()-c.startedAt):0))}
function clockText(ms){const t=Math.floor(ms/1000),pad=n=>String(n).padStart(2,"0");return pad(Math.floor(t/3600))+":"+pad(Math.floor(t/60)%60)+":"+pad(t%60)}
function renderWeight(){progress.bodyweights ||= {};const current=progress.bodyweights[weekKey()];$("weightInput").value=current?String(current.kg).replace(".",","):"";const entries=Object.entries(progress.bodyweights).filter(([,v])=>Number.isFinite(+v.kg)).sort(([a],[b])=>a.localeCompare(b)).slice(-12),chart=$("weightChart");if(!entries.length){chart.innerHTML='<p class="caption">La gráfica aparecerá cuando guardes tu primer registro.</p>';$("weightList").textContent="";return}
 const values=entries.map(([,v])=>+v.kg),lo=Math.floor(Math.min(...values)-1),hi=Math.ceil(Math.max(...values)+1),span=Math.max(2,hi-lo),point=(v,i)=>({x:entries.length===1?186:32+i*308/(entries.length-1),y:147-(v-lo)*115/span}),pts=values.map(point),fmt=n=>new Intl.NumberFormat("es-CL",{maximumFractionDigits:1}).format(n);
 chart.innerHTML=`<svg viewBox="0 0 372 190" role="img" aria-label="Gráfica de peso semanal de ${entries.length} registros"><path class="axis" d="M32 25V147H340"/><text x="2" y="29" class="date">${hi}</text><text x="2" y="149" class="date">${lo}</text><polyline class="trend" points="${pts.map(p=>p.x+","+p.y).join(" ")}"/>${pts.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="5"><title>Semana ${entries[i][0]}: ${fmt(values[i])} kg</title></circle><text x="${p.x}" y="${Math.max(17,p.y-12)}" text-anchor="middle">${fmt(values[i])}</text>${entries.length<=6||i%2===0||i===entries.length-1?`<text class="date" x="${p.x}" y="169" text-anchor="middle">${entries[i][0].slice(5)}</text>`:""}`).join("")}</svg>`;
 $("weightList").textContent="ÚLTIMOS REGISTROS: "+entries.slice(-3).map(([k,v])=>k.split("-").reverse().join("/")+" · "+fmt(+v.kg)+" kg").join("  |  ")}
function drawShareCard(){return new Promise((resolve,reject)=>{const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const c=canvas.getContext("2d"),w=thisWeek(),done=PLAN.filter((_,i)=>w.days[i]?.done).length,N=nDias(),cw=Math.min(166,Math.floor(906/N)-18);
 c.fillStyle="#0c0d12";c.fillRect(0,0,1080,1350);const glow=c.createRadialGradient(540,490,60,540,490,700);glow.addColorStop(0,"#57151f");glow.addColorStop(1,"#0c0d12");c.fillStyle=glow;c.fillRect(0,0,1080,1350);c.strokeStyle="#ffd841";c.lineWidth=9;c.strokeRect(28,28,1024,1294);
 const center=(s,y,size,color)=>{c.font=`900 ${size}px Arial, sans-serif`;c.textAlign="center";c.fillStyle=color;c.fillText(s,540,y)};
 const paint=()=>{center(RUTINA.nombre,535,opt("nombreTam",48),"#ffd841");center(DEMO?"WGYMADNSPORT":memberName.slice(0,28),600,36,"#fff");center(done+" / "+N,815,205,"#ffd841");center("ENTRENAMIENTOS COMPLETADOS",872,36,"#fff");
  PLAN.forEach((d,i)=>{const x=Math.round(540-(N*(cw+18)-18)/2)+i*(cw+18),ok=!!w.days[i]?.done;c.fillStyle=ok?"#ffd841":"#272932";c.fillRect(x,930,cw,140);c.textAlign="center";c.font="900 31px Arial";c.fillStyle=ok?"#191a1e":"#ddd";c.fillText(d.weekday.slice(0,3).toUpperCase(),x+cw/2,985);c.font="900 48px Arial";c.fillText(ok?"✓":"·",x+cw/2,1040)});
  center("LA PERSEVERANCIA ES EL SECRETO",1150,37,"#fff");center("DE TU ÉXITO",1205,42,"#ffd841");center("LA ADMINISTRACIÓN · TOCOPILLA",1280,27,"#aaa");$("sharePreview").src=canvas.toDataURL("image/png");canvas.toBlob(b=>b?resolve(b):reject(Error("No se pudo crear la tarjeta")),"image/png")};
 const logo=new Image();logo.onload=()=>{c.drawImage(logo,175,85,730,405);paint()};logo.onerror=paint;logo.src=document.querySelector(".top img").src})}
function renderClock(){const c=clockState();$("clockTitle").textContent="CRONÓMETRO · "+PLAN[currentDay].weekday.toUpperCase();$("clockFace").textContent=clockText(clockElapsed(c));$("clockCaption").textContent=c.ended?"Sesión terminada. El tiempo quedó guardado en este celular.":c.running?"Sesión en marcha · objetivo aproximado: 60 minutos":c.elapsed?"Sesión en pausa":"Mide el tiempo real de tu sesión.";$("clockStart").textContent=c.ended?"NUEVA SESIÓN":c.elapsed?"REANUDAR":"INICIAR";$("clockStart").disabled=c.running;$("clockPause").disabled=!c.running;$("clockEnd").disabled=c.ended||(!c.running&&!c.elapsed)}
function pauseClock(c){if(c.running){c.elapsed=clockElapsed(c);c.running=false;c.startedAt=null}}
function endClock(){const c=clockState();pauseClock(c);if(c.elapsed){c.ended=true;save()}renderClock()}
function cardioDefault(d){return /bicicleta/i.test(d.warmup)?"bike":/remadora/i.test(d.warmup)?"row":"treadmill"}
function renderCardio(){if(opt("cardio","elegir")==="texto"){const d=PLAN[currentDay];$("cardio").innerHTML=`<b>${esc((d.cooldownTitle||opt("cardioTitulo","ESTIRAMIENTO FINAL")).toUpperCase())}</b><p style="margin:5px 0">${esc(d.cooldown||"")}</p>${d.cooldownVideo?`<video class="pose-video" src="${esc(d.cooldownVideo)}" controls loop muted playsinline preload="metadata"></video>`:""}`;return}const d=PLAN[currentDay],w=thisWeek();w.cardio ||= {};const selected=w.cardio[currentDay]||cardioDefault(d),names={bike:"BICICLETA",row:"REMADORA",treadmill:"TROTADORA CURVA"},end=parseInt(d.cooldown.match(/\d+\s*minutos?/i)?.[0]||"8",10),warm=6;
 const details={bike:`${warm} min suaves para preparar el cuerpo. Al terminar las pesas, ${end} min a ritmo moderado en bicicleta spinning.`,row:`${warm} min suaves para preparar el cuerpo. Al terminar las pesas, ${end} min a ritmo moderado en remadora, manteniendo una técnica fluida.`,treadmill:`${warm} min de caminata suave para preparar el cuerpo. Al terminar las pesas, ${end} min de caminata en trotadora curva a un ritmo cómodo; usa apoyo al subir y bajar.`};
 $("cardio").innerHTML=`<b>CARDIO Y PREPARACIÓN</b><p style="margin:5px 0">Elige la máquina para este día:</p><div class="cardio-choice">${Object.entries(names).map(([key,label])=>`<button type="button" data-cardio="${key}" aria-pressed="${selected===key}">${label}</button>`).join("")}</div><div class="cardio-instructions">${details[selected]}</div>`;
 $("cardio").querySelectorAll("button").forEach(b=>b.onclick=()=>{w.cardio[currentDay]=b.dataset.cardio;save();renderCardio()})}
function exerciseDone(i){const sets=thisWeek().sets;return Array.from({length:nSeries(currentDay,i)},(_,n)=>n).every(n=>sets[currentDay+"_"+i+"_"+n]?.done)}
function renderExerciseMap(){if(!$("mapPoints"))return;const total=PLAN[currentDay].exercises.length,done=Array.from({length:total},(_,i)=>exerciseDone(i));$("mapSummary").textContent=done.filter(Boolean).length+" DE "+total+" EJERCICIOS COMPLETADOS · TOCA UN NÚMERO PARA ABRIRLO";$("mapPoints").style.gridTemplateColumns="repeat("+total+",1fr)";$("mapPoints").innerHTML=done.map((yes,i)=>`<button type="button" class="map-point ${yes?"complete":""}" data-map="${i}" aria-label="Ejercicio ${i+1}: ${esc(PLAN[currentDay].exercises[i].name)}; ${yes?"3 series completadas":"pendiente"}">${yes?"✓":i+1}</button>`).join("");$("mapPoints").querySelectorAll("button").forEach(b=>b.onclick=()=>openExercise(+b.dataset.map));$("trainingProgress").querySelectorAll(".training-dots span").forEach((el,i)=>{el.className=(done[i]?"done ":"")+(i===currentEx?"active":"")})}
function render(){const days=PLAN,w=thisWeek();renderDashboard();$("days").innerHTML=days.map((d,i)=>`<button class="day" aria-selected="${i===currentDay}" data-day="${i}"><b>${esc(d.weekday)} ${w.days[i]?.done?"✓":""}</b><small>DÍA ${String(i+1).padStart(2,"0")}</small></button>`).join("");
 const d=days[currentDay];$("weekday").textContent="DÍA "+String(currentDay+1).padStart(2,"0")+" · "+d.weekday.toUpperCase();$("sessionTitle").textContent=d.title;$("focus").textContent=d.focus;
 $("exercises").innerHTML=d.exercises.map((x,i)=>`<button class="row" data-ex="${i}"><span class="body"><strong>${esc(x.name)}</strong><small>${esc(x.sets)} · ${esc(x.equip)}</small></span><span class="arrow">→</span></button>`).join("");
 renderCardio();renderExerciseMap();
 $("count").textContent=String(Object.values(w.sets).filter(x=>x.done).length).padStart(2,"0");$("finishDay").textContent=w.days[currentDay]?.done?"✓ ENTRENAMIENTO COMPLETADO · TOCA PARA DESHACER":"TERMINÉ MI ENTRENAMIENTO";$("finishDay").classList.toggle("complete",!!w.days[currentDay]?.done);
 renderClock();$("days").querySelectorAll("button").forEach(b=>b.onclick=()=>{currentDay=+b.dataset.day;render()});$("exercises").querySelectorAll("button").forEach(b=>b.onclick=()=>openExercise(+b.dataset.ex))}
function pairVisual(x,name){const v=opt("visual","pares");
 if(v==="video")return `<div style="width:100%"><video class="pose-video" src="${esc(x.video)}" controls loop muted playsinline preload="metadata" aria-label="Video de la técnica: ${esc(name)}"></video><figcaption>TOCA PLAY PARA VER LA TÉCNICA</figcaption></div>`;
 if(v==="imagen")return `<div class="pose-single"><img class="pose-image" role="button" tabindex="0" aria-label="Ampliar ${esc(name)}" alt="${esc(name)}" src="${esc(x.img[0])}"></div><figcaption>TOCA LA IMAGEN PARA AMPLIARLA</figcaption></div>`;
 const f={ancho:"wide",alto:"tall",plancha:"plank"}[x.formato]||"";return `<div style="width:100%"><div class="pose-grid ${f}">${[0,1].map(row=>`<div class="pose-cell"><span class="pose-label">${row?"FINAL":"INICIO"}</span><img class="pose-image" role="button" tabindex="0" data-pose="${row?"FINAL":"INICIO"}" aria-label="Ampliar ${esc(name)} · posición ${row?"final":"inicial"}" alt="${esc(name)} · posición ${row?"final":"inicial"}" src="${esc(x.img[row])}"></div>`).join("")}</div><figcaption>TOCA UNA IMAGEN PARA AMPLIARLA</figcaption></div>`}
let zoomReturn=null;
function openImageZoom(el){zoomReturn=el;const view=$("imageZoomView");view.src=el.src;view.alt=el.alt;if(opt("visual","pares")==="imagen"){view.className="image-zoom-view";$("imageZoomLabel").textContent=(el.alt||"").toUpperCase();$("imageZoom").classList.add("open");$("imageZoomClose").focus();return}view.className="image-zoom-view"+(el.closest(".tall")?" tall":"");$("imageZoomLabel").textContent=PLAN[currentDay].exercises[currentEx].name.toUpperCase()+" · "+el.dataset.pose;$("imageZoom").classList.add("open");$("imageZoomClose").focus()}
function closeImageZoom(){$("imageZoom").classList.remove("open");zoomReturn?.focus();zoomReturn=null}
$("stage").addEventListener("click",e=>{const el=e.target.closest(".pose-image");if(el)openImageZoom(el)});
$("stage").addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches(".pose-image")){e.preventDefault();openImageZoom(e.target)}});
$("imageZoomClose").onclick=closeImageZoom;$("imageZoom").onclick=e=>{if(e.target===$("imageZoom"))closeImageZoom()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("imageZoom").classList.contains("open"))closeImageZoom()});
function openExercise(i){clearInterval(countdown);currentEx=i;const x=PLAN[currentDay].exercises[i],total=PLAN[currentDay].exercises.length;$("trainingProgress").innerHTML=`EJERCICIO ${i+1} DE ${total}<div class="training-dots" aria-hidden="true">${Array.from({length:total},()=>`<span></span>`).join("")}</div>`;renderExerciseMap();$("trainingPrev").hidden=i===0;$("trainingNext").textContent=i===total-1?"TERMINAR ENTRENAMIENTO ✓":"SIGUIENTE EJERCICIO →";$("exDay").textContent=PLAN[currentDay].weekday.toUpperCase()+" · EJERCICIO "+(i+1);$("exTitle").textContent=x.name;$("muscles").textContent="● "+x.muscle;$("tags").innerHTML=[x.sets,"DESCANSO "+x.rest,x.equip].map(t=>`<span class="tag">${esc(t)}</span>`).join("");$("tip").textContent=x.tip;$("occupied").hidden=!/máquina|prensa|polea|barra guiada/i.test(x.equip)&&!/jalón al pecho|press de pecho sentado|remo bajo|curl femoral|extensión de glúteo a una pierna|press militar|remo frontal|sentadilla en smith/i.test(x.name);
 $("stage").innerHTML=pairVisual(x,x.name);
 const plank=norm(x.name)==="PLANCHA FRONTAL";$("repsLabel").textContent=plank?"Segundos":"Reps";
 const count=nSeries(currentDay,i),base=currentDay+"_"+i,sets=thisWeek().sets;$("sets").innerHTML=Array.from({length:count},(_,n)=>{const v=sets[base+"_"+n]||{};return `<div class="set" data-set="${n}"><span>${n+1}</span><input inputmode="decimal" aria-label="Peso serie ${n+1}" placeholder="${plank?"—":"kg"}" ${plank?"disabled":""} value="${esc(v.kg||"")}"><input inputmode="numeric" aria-label="${plank?"Segundos":"Repeticiones"} serie ${n+1}" placeholder="${plank?"seg":"reps"}" value="${esc(v.reps||"")}"><button aria-label="Marcar serie ${n+1}" class="${v.done?"done":""}">✓</button></div>`}).join("");
 $("sets").querySelectorAll(".set").forEach(row=>{const n=+row.dataset.set,k=base+"_"+n,inputs=row.querySelectorAll("input"),btn=row.querySelector("button");function update(){sets[k]={kg:inputs[0].value,reps:inputs[1].value,done:btn.classList.contains("done")};save();intensity();renderExerciseMap()}inputs.forEach(e=>e.oninput=update);btn.onclick=()=>{btn.classList.toggle("done");update()}});intensity();$("timer").hidden=!(parseInt(x.rest,10)>0);$("timer").textContent="Iniciar descanso · "+x.rest;$("timer").classList.remove("finished");$("restStatus").textContent="";$("overlay").classList.add("open");$("overlay").scrollTop=0;document.body.style.overflow="hidden"}
function intensity(){$("intensity").textContent="TU MEJOR MARCA: "+bestFor(currentDay,currentEx)}
function close(){clearInterval(countdown);$("overlay").classList.remove("open");document.body.style.overflow="";render()}
function restChime(){try{if(!audioCtx)return;audioCtx.resume();for(const [i,hz] of [740,980].entries()){const o=audioCtx.createOscillator(),g=audioCtx.createGain(),at=audioCtx.currentTime+i*.25;o.type="sine";o.frequency.value=hz;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.12,at+.025);g.gain.exponentialRampToValueAtTime(.0001,at+.2);o.connect(g).connect(audioCtx.destination);o.start(at);o.stop(at+.22)}}catch{}try{navigator.vibrate?.([180,90,180])}catch{}}
$("back").onclick=close;$("enter").onclick=login;$("welcomeSkip").onclick=saltarBienvenida;$("member").onkeydown=e=>{if(e.key==="Enter")login()};$("userpill").onclick=()=>{if(!DEMO){memberName="";$("app").hidden=true;$("login").hidden=false}};
$("trainingPrev").onclick=()=>{if(currentEx>0)openExercise(currentEx-1)};$("trainingNext").onclick=()=>{if(currentEx+1<PLAN[currentDay].exercises.length)openExercise(currentEx+1);else{close();if(!thisWeek().days[currentDay]?.done)$("finishDay").click()}};
$("showRecords").onclick=()=>{$("recordPanel").hidden=!$("recordPanel").hidden;$("historyPanel").hidden=true};$("showHistory").onclick=()=>{$("historyPanel").hidden=!$("historyPanel").hidden;$("recordPanel").hidden=true};
$("showShare").onclick=async()=>{$("shareScreen").classList.add("open");$("shareHint").textContent="Preparando tu tarjeta...";$("shareSend").disabled=true;try{shareBlob=await drawShareCard();$("shareHint").textContent="Al compartir, elige WhatsApp en el menú de tu celular.";$("shareSend").disabled=false}catch{$("shareHint").textContent="No se pudo preparar la tarjeta. Inténtalo de nuevo."}};
$("shareClose").onclick=()=>{$("shareScreen").classList.remove("open");$("showShare").focus()};
$("shareSend").onclick=async()=>{if(!shareBlob)return;const filename="WGYMADNSPORT-mi-semana.png",file=typeof File!=="undefined"?new File([shareBlob],filename,{type:"image/png"}):null;if(file&&navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:"Mi semana en WGYMADNSPORT",text:"La perseverancia es el secreto de tu éxito"});return}catch(e){if(e.name==="AbortError")return}}
 const a=document.createElement("a");a.href=$("sharePreview").src;a.download=filename;document.body.appendChild(a);a.click();a.remove();$("shareHint").textContent="Tarjeta descargada. Abre WhatsApp y adjunta la imagen."};
$("clockStart").onclick=()=>{const k=weekKey();progress.clocks ||= {};for(const [day,c] of Object.entries(progress.clocks[k]||{}))if(+day!==currentDay)pauseClock(c);const c=clockState();if(c.ended){c.elapsed=0;c.ended=false}c.startedAt=Date.now();c.running=true;save();renderClock()};
$("clockPause").onclick=()=>{pauseClock(clockState());save();renderClock()};$("clockEnd").onclick=endClock;
$("weightToggle").onclick=()=>{const open=$("weightChart").hidden;$("weightChart").hidden=!open;$("weightList").hidden=!open;$("weightToggle").textContent=open?"CERRAR GRÁFICA":"VER MI EVOLUCIÓN";$("weightToggle").setAttribute("aria-expanded",String(open))};
$("weightForm").onsubmit=e=>{e.preventDefault();const raw=$("weightInput").value.trim().replace(",","."),kg=Number(raw);if(!raw||!Number.isFinite(kg)||kg<20||kg>400){$("weightStatus").textContent="Escribe un peso válido en kilos, por ejemplo 63,5.";return}progress.bodyweights ||= {};progress.bodyweights[weekKey()]={kg:Math.round(kg*10)/10,recordedAt:new Date().toISOString()};save();renderWeight();$("weightChart").hidden=true;$("weightList").hidden=true;$("weightToggle").textContent="VER MI EVOLUCIÓN";$("weightToggle").setAttribute("aria-expanded","false");$("weightStatus").textContent="Peso semanal guardado. La gráfica se cerró; puedes abrirla cuando quieras."};
function showSessionSummary(){const sets=thisWeek().sets,entries=PLAN[currentDay].exercises.flatMap((_,i)=>Array.from({length:nSeries(currentDay,i)},(_,n)=>({exercise:i,value:sets[currentDay+"_"+i+"_"+n]}))),completed=entries.filter(x=>x.value?.done),withWeight=completed.map(x=>({name:PLAN[currentDay].exercises[x.exercise].name,kg:Number(String(x.value.kg||"").replace(",","."))})).filter(x=>Number.isFinite(x.kg)&&x.kg>0).sort((a,b)=>b.kg-a.kg),ms=clockElapsed(clockState());$("summaryTime").textContent=ms?clockText(ms):"—";$("summarySets").textContent=completed.length+" / "+entries.length;$("summaryBest").innerHTML=withWeight.length?`<b>MAYOR CARGA REGISTRADA</b><br>${esc(withWeight[0].name)} · ${withWeight[0].kg} kg`:"MAYOR CARGA REGISTRADA<br>Sin peso anotado en esta sesión";$("sessionSummary").classList.add("open");$("summaryContinue").focus()}
$("finishDay").onclick=()=>{const w=thisWeek(),wasDone=!!w.days[currentDay]?.done;if(!wasDone&&clockState().running)endClock();w.days[currentDay]={done:!wasDone,completedAt:wasDone?null:new Date().toISOString()};save();render();if(!wasDone){const done=Object.values(w.days).filter(x=>x.done).length;const N=nDias();$("celebrateTitle").textContent=done===N?"¡SEMANA COMPLETADA!":"¡LO LOGRASTE!";$("celebrate").querySelector(".star").textContent=done===N?"🏅":"★";$("celebrateProgress").textContent=done===N?"GANASTE TU MEDALLA DIGITAL · "+N+" DE "+N+" DÍAS":done+" DE "+N+" ENTRENAMIENTOS COMPLETADOS ESTA SEMANA";if(done===N&&streakCount()>1)$("celebrateProgress").textContent+=" · RACHA DE "+streakCount()+" SEMANAS";showSessionSummary()}};
$("summaryContinue").onclick=()=>{$("sessionSummary").classList.remove("open");$("celebrate").classList.add("open");$("celebrateClose").focus()};
$("celebrateClose").onclick=()=>{$("celebrate").classList.remove("open");$("finishDay").focus()};
setInterval(()=>{if(!$("app").hidden)renderClock()},1000);
$("timer").onclick=()=>{clearInterval(countdown);try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}const seconds=parseInt(PLAN[currentDay].exercises[currentEx].rest,10),deadline=Date.now()+seconds*1000,btn=$("timer");btn.classList.remove("finished");$("restStatus").textContent="";btn.textContent="Descanso · "+seconds+" s";countdown=setInterval(()=>{const sec=Math.ceil((deadline-Date.now())/1000);btn.textContent=sec>0?"Descanso · "+sec+" s":"¡Descanso terminado!";if(sec<=0){clearInterval(countdown);btn.classList.add("finished");$("restStatus").textContent="LISTA PARA LA SIGUIENTE SERIE";restChime()}},250)};
if(DEMO){rutinaLista.then(start)}else{$("login").hidden=false}
