/* Recetario saludable de WGYMNUTRI (10/2026). Recetas simples y generales
   (no son las de comidas-saludables.html: la dueña pidió un recetario
   aparte). Calorías y macros por porción, calculados con los valores de
   nutri-alimentos.js; son aproximados.
   k = kcal, p = proteína g, c = carbohidratos g, g = grasas g. */
window.NUTRI_RECETAS = [
 { n:"Avena proteica con plátano", cat:"Desayuno", e:"🥣", min:5, porc:"1 bowl", k:332, p:25, c:52, g:4,
   ing:["40 g de avena (1/2 taza)","200 ml de leche descremada","1/2 plátano en rodajas","1/2 scoop de proteína whey (15 g)","Canela a gusto"],
   pasos:["Calienta la leche con la avena 3 minutos, revolviendo.","Retira del fuego y deja enfriar 1 minuto.","Agrega la proteína y revuelve hasta que no queden grumos (si la pones hirviendo se corta).","Cubre con el plátano y la canela."] },
 { n:"Omelette de claras con espinaca y quesillo", cat:"Desayuno", e:"🍳", min:10, porc:"1 omelette + 1 pan integral", k:308, p:30, c:18, g:13,
   ing:["1 huevo entero y 3 claras","1/2 taza de espinaca","50 g de quesillo","1 cucharadita de aceite","1 rebanada de pan integral","Sal y pimienta"],
   pasos:["Bate el huevo con las claras, sal y pimienta.","Saltea la espinaca 1 minuto en el sartén con el aceite.","Vierte los huevos, cocina a fuego bajo y agrega el quesillo en la mitad.","Dobla el omelette y sirve con el pan tostado."] },
 { n:"Pan integral con palta y huevo", cat:"Desayuno", e:"🥑", min:10, porc:"2 rebanadas", k:260, p:14, c:27, g:11,
   ing:["2 rebanadas de pan integral","2 cucharadas de palta","1 huevo","Tomate en rodajas (opcional)","Sal y orégano"],
   pasos:["Cuece el huevo 9 minutos y pélalo.","Tuesta el pan.","Unta la palta, agrega el tomate y el huevo en láminas.","Termina con sal y orégano."] },
 { n:"Yogur proteico con frutillas y almendras", cat:"Colación", e:"🍓", min:3, porc:"1 pote", k:183, p:18, c:16, g:6,
   ing:["1 yogur proteico (160 g)","1/2 taza de frutillas picadas","10 g de almendras picadas"],
   pasos:["Sirve el yogur en un pote.","Agrega las frutillas y las almendras encima."] },
 { n:"Batido verde de proteína", cat:"Colación", e:"🥤", min:3, porc:"1 vaso grande", k:232, p:26, c:31, g:2,
   ing:["1 scoop de proteína whey (30 g)","1 plátano","1 taza de espinaca cruda","250 ml de agua fría o hielo"],
   pasos:["Pon todo en la licuadora.","Licúa 30 a 40 segundos hasta que quede liso.","Tómalo después de entrenar."] },
 { n:"Manzana con mantequilla de maní", cat:"Colación", e:"🍎", min:2, porc:"1 manzana", k:190, p:4, c:29, g:8,
   ing:["1 manzana","1 cucharada de mantequilla de maní","Canela (opcional)"],
   pasos:["Corta la manzana en gajos.","Úntalos con la mantequilla de maní y espolvorea canela."] },
 { n:"Bowl de pollo, arroz integral y verduras", cat:"Almuerzo", e:"🍗", min:25, porc:"1 bowl", k:477, p:45, c:50, g:11,
   ing:["120 g de pechuga de pollo","3/4 taza de arroz integral cocido","1 taza de brócoli","1/2 taza de zanahoria rallada","1 cucharadita de aceite de oliva","Ajo, comino, sal y limón"],
   pasos:["Condimenta el pollo con ajo, comino y sal, y cocínalo a la plancha 5 a 6 minutos por lado.","Cuece el brócoli al vapor 4 minutos.","Arma el bowl con el arroz, el pollo en tiras, el brócoli y la zanahoria.","Aliña con el aceite de oliva y limón."] },
 { n:"Ensalada de atún, garbanzos y tomate", cat:"Almuerzo", e:"🥗", min:10, porc:"1 plato grande", k:342, p:39, c:30, g:8,
   ing:["1 lata de atún en agua","1/2 taza de garbanzos cocidos","1 tomate","Lechuga a gusto","1 cucharadita de aceite de oliva","Limón, cebollín y sal"],
   pasos:["Escurre el atún y enjuaga los garbanzos.","Pica el tomate, la lechuga y el cebollín.","Mezcla todo en un bowl.","Aliña con aceite, limón y sal."] },
 { n:"Carne salteada con verduras y arroz", cat:"Almuerzo", e:"🥩", min:20, porc:"1 plato", k:411, p:38, c:36, g:12,
   ing:["120 g de posta en tiras","1 1/2 taza de pimentón, cebolla y porotos verdes","1/2 taza de arroz blanco cocido","1 cucharadita de aceite","Salsa de soya baja en sodio, ajo y jengibre"],
   pasos:["Calienta el sartén bien caliente con el aceite.","Saltea la carne 2 a 3 minutos y retírala.","Saltea las verduras 4 minutos con ajo y jengibre.","Devuelve la carne, agrega un chorrito de soya y sirve con el arroz."] },
 { n:"Lentejas con verduras", cat:"Almuerzo", e:"🍲", min:35, porc:"1 plato", k:310, p:19, c:49, g:6,
   ing:["1 taza de lentejas cocidas","1/2 zanahoria y 1/2 zapallo italiano en cubos","1/4 de cebolla y 1 diente de ajo","1 cucharadita de aceite","Comino, pimentón y sal"],
   pasos:["Sofríe la cebolla y el ajo en el aceite.","Agrega la zanahoria y el zapallo, y cocina 5 minutos.","Suma las lentejas, 1 taza de agua y los condimentos.","Cocina 15 minutos a fuego bajo hasta que espese."] },
 { n:"Salmón al horno con camote", cat:"Cena", e:"🐟", min:30, porc:"1 plato", k:398, p:31, c:34, g:16,
   ing:["120 g de salmón","1 camote mediano (150 g)","Ensalada de lechuga","Limón, eneldo, sal y pimienta"],
   pasos:["Precalienta el horno a 200 °C.","Corta el camote en bastones y hornéalo 15 minutos.","Agrega el salmón condimentado a la bandeja y hornea 12 minutos más.","Sirve con la ensalada y limón."] },
 { n:"Tortilla de zapallo italiano al horno", cat:"Cena", e:"🥚", min:25, porc:"1 porción", k:253, p:20, c:9, g:16,
   ing:["2 huevos","1 zapallo italiano rallado","1/4 de cebolla picada","1 lámina de queso gauda","Sal, pimienta y orégano"],
   pasos:["Precalienta el horno a 180 °C.","Bate los huevos y mezcla con el zapallo, la cebolla y los condimentos.","Vierte en un molde pequeño y pon el queso encima.","Hornea 18 a 20 minutos, hasta que esté firme."] },
 { n:"Wrap de pavo y verduras", cat:"Cena", e:"🌯", min:8, porc:"1 wrap", k:257, p:29, c:25, g:4,
   ing:["1 tortilla de trigo","80 g de pechuga de pavo","Lechuga y tomate","1 cucharada de yogur natural","Mostaza (opcional)"],
   pasos:["Calienta la tortilla 20 segundos en el sartén.","Unta el yogur y la mostaza.","Agrega el pavo, la lechuga y el tomate.","Enrolla apretando bien y corta por la mitad."] },
 { n:"Mousse de yogur y cacao", cat:"Postre", e:"🍫", min:5, porc:"1 pote", k:112, p:16, c:10, g:1,
   ing:["1 yogur proteico natural (160 g)","1 cucharadita de cacao amargo","Endulzante a gusto"],
   pasos:["Mezcla el yogur con el cacao y el endulzante.","Bate con un tenedor hasta que quede cremoso.","Enfría 10 minutos antes de comer."] },
 /* Agregadas el 10-10-2026 (la dueña pidió más recetas). */
 { n:"Huevos revueltos con tomate y pan pita", cat:"Desayuno", e:"🍅", min:8, porc:"2 huevos + 1 pita", k:320, p:19, c:36, g:11,
   ing:["2 huevos","1/2 tomate picado","1 pan pita integral","Sal, pimienta y cebollín"],
   pasos:["Calienta un sartén antiadherente y saltea el tomate 1 minuto.","Agrega los huevos batidos y revuelve a fuego bajo hasta que cuajen.","Calienta la pita y rellénala con los huevos.","Termina con cebollín picado."] },
 { n:"Panqueques de avena y plátano", cat:"Desayuno", e:"🥞", min:15, porc:"3 panqueques", k:344, p:16, c:55, g:8,
   ing:["40 g de avena","1 plátano maduro","1 huevo y 1 clara","Canela y 1 pizca de polvos de hornear"],
   pasos:["Licúa todos los ingredientes hasta tener una mezcla espesa.","Calienta un sartén antiadherente a fuego medio.","Pon 3 cucharadas de mezcla por panqueque y cocina 2 minutos por lado.","Sirve con canela o unas frutillas."] },
 { n:"Pudding de chía con frutillas", cat:"Desayuno", e:"🍮", min:5, porc:"1 vaso", k:191, p:11, c:24, g:7,
   ing:["2 cucharadas de chía (20 g)","200 ml de leche descremada","1/2 taza de frutillas","Endulzante y vainilla a gusto"],
   pasos:["Mezcla la chía con la leche, la vainilla y el endulzante.","Revuelve bien y deja en el refrigerador toda la noche (o mínimo 2 horas).","En la mañana agrega las frutillas picadas."] },
 { n:"Tostadas con quesillo y tomate", cat:"Once", e:"🍞", min:5, porc:"2 tostadas", k:217, p:15, c:30, g:4,
   ing:["2 rebanadas de pan integral","50 g de quesillo","1 tomate en rodajas","Orégano y sal"],
   pasos:["Tuesta el pan.","Pon el quesillo en láminas y el tomate encima.","Termina con orégano y una pizca de sal."] },
 { n:"Pan pita con pollo y palta", cat:"Once", e:"🥙", min:10, porc:"1 pita", k:345, p:31, c:36, g:9,
   ing:["1 pan pita integral","80 g de pollo cocido desmenuzado","2 cucharadas de palta","Lechuga y tomate"],
   pasos:["Calienta la pita y ábrela por un costado.","Unta la palta por dentro.","Rellena con el pollo, la lechuga y el tomate."] },
 { n:"Pollo al horno con papas y ensalada chilena", cat:"Almuerzo", e:"🍗", min:45, porc:"1 plato", k:453, p:50, c:38, g:10,
   ing:["150 g de pechuga o trutro sin piel","1 papa mediana en gajos","1 plato de ensalada chilena (tomate y cebolla)","1 cucharadita de aceite","Ajo, merkén, orégano y sal"],
   pasos:["Precalienta el horno a 200 °C.","Condimenta el pollo y las papas con ajo, merkén, orégano, sal y el aceite.","Hornea todo junto 35 a 40 minutos, dando vuelta a la mitad.","Sirve con la ensalada chilena."] },
 { n:"Cazuela de pollo liviana", cat:"Almuerzo", e:"🍲", min:40, porc:"1 plato", k:372, p:43, c:40, g:6,
   ing:["120 g de pechuga de pollo","1/2 papa","1 trozo de zapallo","1/2 choclo (o 1/2 taza de granos)","1/2 taza de porotos verdes","Cilantro, ajo, comino y sal"],
   pasos:["Hierve el pollo en 1 litro de agua con ajo, comino y sal por 15 minutos.","Agrega la papa y el zapallo y cocina 10 minutos.","Suma el choclo y los porotos verdes y cocina 8 minutos más.","Sirve con cilantro picado."] },
 { n:"Quínoa con verduras y pollo", cat:"Almuerzo", e:"🥘", min:25, porc:"1 plato", k:412, p:38, c:37, g:11,
   ing:["3/4 taza de quínoa cocida","100 g de pollo en cubos","1 taza de pimentón y zapallo italiano picados","1 cucharadita de aceite","Ajo, cúrcuma y sal"],
   pasos:["Lava bien la quínoa y cuécela 15 minutos en el doble de agua.","Saltea el pollo con el aceite y el ajo hasta dorar.","Agrega las verduras y la cúrcuma y saltea 4 minutos.","Mezcla con la quínoa y ajusta la sal."] },
 { n:"Tallarines integrales con atún y tomate", cat:"Almuerzo", e:"🍝", min:20, porc:"1 plato", k:384, p:38, c:45, g:7,
   ing:["1 taza de tallarines integrales cocidos","1 lata de atún en agua","1/2 taza de salsa de tomate casera","1 cucharadita de aceite de oliva","Ajo y albahaca"],
   pasos:["Cuece los tallarines según el paquete.","Sofríe el ajo en el aceite, agrega la salsa de tomate y cocina 5 minutos.","Suma el atún escurrido y calienta 1 minuto.","Mezcla con los tallarines y termina con albahaca."] },
 { n:"Merluza a la plancha con puré de zapallo", cat:"Cena", e:"🐠", min:25, porc:"1 plato", k:283, p:35, c:30, g:3,
   ing:["150 g de merluza o reineta","1 taza de zapallo cocido","1/2 papa cocida","50 ml de leche descremada","Limón, ajo, sal y nuez moscada"],
   pasos:["Cuece el zapallo y la papa hasta que estén blandos y muélelos con la leche, sal y nuez moscada.","Condimenta el pescado con limón, ajo y sal.","Cocínalo en un sartén antiadherente 3 a 4 minutos por lado.","Sirve sobre el puré."] },
 { n:"Ensalada César liviana con pollo", cat:"Cena", e:"🥬", min:15, porc:"1 plato grande", k:330, p:44, c:15, g:9,
   ing:["120 g de pechuga de pollo a la plancha","2 tazas de lechuga","2 cucharadas de yogur natural con limón y ajo (salsa)","10 g de queso parmesano","15 g de crutones"],
   pasos:["Cocina el pollo a la plancha y córtalo en tiras.","Mezcla el yogur con limón, ajo y una pizca de sal para la salsa.","Arma la ensalada con la lechuga, el pollo y los crutones.","Aliña con la salsa y espolvorea el parmesano."] },
 { n:"Hamburguesa casera de pavo con ensalada", cat:"Cena", e:"🍔", min:20, porc:"1 hamburguesa", k:268, p:29, c:10, g:13,
   ing:["120 g de pavo molido","Lechuga y tomate","2 cucharadas de palta","Ajo, cebolla en polvo, sal y pimienta"],
   pasos:["Mezcla el pavo con los condimentos y forma una hamburguesa.","Cocínala en un sartén antiadherente 5 minutos por lado.","Sírvela sobre la lechuga y el tomate, con la palta encima."] },
 { n:"Porotos verdes salteados con huevo", cat:"Cena", e:"🫛", min:15, porc:"1 plato", k:250, p:16, c:16, g:15,
   ing:["1 1/2 taza de porotos verdes","2 huevos","1 cucharadita de aceite","Ajo, sal y pimienta"],
   pasos:["Cuece los porotos verdes 5 minutos y escúrrelos.","Saltéalos con el aceite y el ajo 3 minutos.","Agrega los huevos batidos y revuelve hasta que cuajen."] },
 { n:"Garbanzos asados crocantes", cat:"Colación", e:"🫘", min:30, porc:"1/2 taza", k:155, p:7, c:23, g:4,
   ing:["1/2 taza de garbanzos cocidos","1/2 cucharadita de aceite","Pimentón, comino y sal"],
   pasos:["Seca muy bien los garbanzos con papel absorbente.","Mézclalos con el aceite y los condimentos.","Hornea a 200 °C por 25 minutos, moviendo la bandeja a la mitad, hasta que estén crocantes."] },
 { n:"Huevos duros con palta", cat:"Colación", e:"🥚", min:12, porc:"2 huevos", k:192, p:13, c:3, g:14,
   ing:["2 huevos","2 cucharadas de palta","Sal y merkén"],
   pasos:["Cuece los huevos 9 minutos y pélalos.","Córtalos por la mitad y pon la palta encima.","Termina con sal y merkén."] },
 { n:"Batido de frutilla y avena", cat:"Colación", e:"🍹", min:3, porc:"1 vaso grande", k:271, p:24, c:39, g:3,
   ing:["250 ml de leche descremada","1 taza de frutillas","20 g de avena","1/2 scoop de proteína whey (15 g)"],
   pasos:["Pon todo en la licuadora.","Licúa hasta que quede cremoso.","Sirve frío."] },
 { n:"Helado de plátano y cacao", cat:"Postre", e:"🍨", min:5, porc:"1 pote", k:117, p:2, c:29, g:1,
   ing:["1 plátano congelado en rodajas","1 cucharadita de cacao amargo"],
   pasos:["Congela el plátano en rodajas mínimo 3 horas.","Muélelo en la licuadora o procesadora con el cacao hasta que quede como helado.","Cómelo al tiro."] },
 { n:"Manzana asada con canela y yogur", cat:"Postre", e:"🍏", min:20, porc:"1 manzana", k:150, p:6, c:32, g:1,
   ing:["1 manzana","Canela a gusto","1 yogur natural light (125 g)"],
   pasos:["Corta la manzana en cubos y espolvorea canela.","Cocínala en el microondas 3 a 4 minutos (o al horno 15 minutos).","Sirve tibia con el yogur encima."] },
 /* Agregadas el 10-10-2026, segunda tanda (la dueña pidió llegar a 50). */
 { n:"Avena remojada con manzana y canela", cat:"Desayuno", e:"🍎", min:5, porc:"1 frasco", k:288, p:14, c:52, g:3,
   ing:["40 g de avena","1 yogur natural light (125 g)","100 ml de leche descremada","1/2 manzana picada","Canela a gusto"],
   pasos:["Mezcla en un frasco la avena, el yogur y la leche.","Agrega la manzana y la canela.","Tapa y deja en el refrigerador toda la noche. En la mañana está lista."] },
 { n:"Wrap de huevo y espinaca", cat:"Desayuno", e:"🌯", min:10, porc:"1 wrap", k:284, p:18, c:24, g:13,
   ing:["1 tortilla de trigo","2 huevos","1/2 taza de espinaca","Sal y pimienta"],
   pasos:["Saltea la espinaca 1 minuto en un sartén antiadherente.","Agrega los huevos batidos y revuelve hasta que cuajen.","Calienta la tortilla, rellena y enrolla."] },
 { n:"Tostadas con mantequilla de maní y plátano", cat:"Desayuno", e:"🍌", min:5, porc:"2 tostadas", k:287, p:11, c:41, g:10,
   ing:["2 rebanadas de pan integral","1 cucharada de mantequilla de maní","1/2 plátano en rodajas","Canela (opcional)"],
   pasos:["Tuesta el pan.","Unta la mantequilla de maní.","Pon el plátano encima y espolvorea canela."] },
 { n:"Sándwich de pavo y quesillo", cat:"Once", e:"🥪", min:5, porc:"1 sándwich", k:255, p:22, c:30, g:5,
   ing:["2 rebanadas de pan integral","2 láminas de jamón de pavo","50 g de quesillo","Lechuga y tomate"],
   pasos:["Tuesta el pan si te gusta crujiente.","Arma el sándwich con el pavo, el quesillo, la lechuga y el tomate."] },
 { n:"Media marraqueta con huevo y tomate", cat:"Once", e:"🥖", min:8, porc:"1/2 marraqueta", k:218, p:11, c:31, g:6,
   ing:["1/2 marraqueta","1 huevo","1/2 tomate en rodajas","Sal y orégano"],
   pasos:["Revuelve el huevo en un sartén antiadherente, sin aceite.","Tuesta la media marraqueta.","Pon el tomate y el huevo encima, con sal y orégano."] },
 { n:"Pescado al jugo con verduras", cat:"Almuerzo", e:"🐟", min:25, porc:"1 plato", k:343, p:34, c:33, g:8,
   ing:["150 g de reineta o merluza","1 taza de cebolla, pimentón y tomate en pluma","1/2 taza de arroz integral cocido","1 cucharadita de aceite","Ajo, orégano, limón y sal"],
   pasos:["Sofríe la cebolla, el pimentón y el ajo en el aceite 4 minutos.","Agrega el tomate y un chorrito de agua.","Pon el pescado encima, tapa y cocina 8 a 10 minutos a fuego bajo.","Sirve con el arroz y limón."] },
 { n:"Charquicán liviano", cat:"Almuerzo", e:"🥔", min:35, porc:"1 plato", k:363, p:28, c:39, g:12,
   ing:["90 g de carne molida magra","1/2 papa","1 taza de zapallo","1/4 taza de choclo","1/2 taza de porotos verdes","Cebolla, ajo, comino y sal"],
   pasos:["Dora la carne con la cebolla y el ajo, sin aceite extra.","Agrega la papa, el zapallo y 1/2 taza de agua, y cocina 15 minutos.","Suma el choclo y los porotos verdes y cocina 5 minutos más.","Muele un poco con un tenedor y sirve. Puedes agregar un huevo a la plancha."] },
 { n:"Porotos con zapallo", cat:"Almuerzo", e:"🫘", min:30, porc:"1 plato", k:244, p:13, c:38, g:5,
   ing:["3/4 taza de porotos cocidos","1/2 taza de zapallo en cubos","1/4 de cebolla","1 cucharadita de aceite","Pimentón, orégano y sal"],
   pasos:["Sofríe la cebolla en el aceite con el pimentón.","Agrega el zapallo y los porotos con 1 taza de agua.","Cocina 15 minutos hasta que el zapallo se deshaga y espese.","Acompaña con ensalada para un plato completo."] },
 { n:"Pechuga rellena de espinaca y quesillo", cat:"Almuerzo", e:"🍗", min:35, porc:"1 pechuga + 1 papa", k:453, p:59, c:35, g:8,
   ing:["150 g de pechuga de pollo","1/2 taza de espinaca","50 g de quesillo","1 papa cocida","Ajo, sal y pimienta"],
   pasos:["Abre la pechuga por la mitad como un libro.","Rellena con la espinaca y el quesillo, y ciérrala con un palito.","Hornea a 200 °C por 25 minutos.","Sirve con la papa cocida."] },
 { n:"Arroz chaufa liviano de pollo", cat:"Almuerzo", e:"🍚", min:20, porc:"1 plato", k:459, p:42, c:38, g:14,
   ing:["3/4 taza de arroz integral cocido (frío)","100 g de pollo en cubos","1 huevo","Cebollín y pimentón picados","1 cucharadita de aceite","Salsa de soya baja en sodio y jengibre"],
   pasos:["Saltea el pollo con el aceite hasta dorar.","Agrega el huevo batido y revuelve.","Suma el arroz, el cebollín, el pimentón y el jengibre.","Termina con un chorrito de soya y saltea 2 minutos más."] },
 { n:"Ensalada de lentejas con queso fresco", cat:"Almuerzo", e:"🥗", min:10, porc:"1 plato", k:410, p:28, c:51, g:13,
   ing:["1 taza de lentejas cocidas","Tomate, pepino y cebolla morada picados","50 g de queso fresco en cubos","1 cucharadita de aceite de oliva","Limón, cilantro y sal"],
   pasos:["Enjuaga y escurre las lentejas.","Mézclalas con las verduras picadas.","Agrega el queso fresco.","Aliña con aceite, limón, cilantro y sal."] },
 { n:"Palta reina liviana", cat:"Cena", e:"🥑", min:10, porc:"1/2 palta", k:197, p:17, c:8, g:11,
   ing:["1/2 palta","1/2 lata de atún en agua","1 cucharada de yogur natural","Lechuga, limón y sal"],
   pasos:["Mezcla el atún con el yogur, limón y sal.","Rellena la media palta con la mezcla.","Sirve sobre hojas de lechuga."] },
 { n:"Zapallo italiano relleno", cat:"Cena", e:"🥒", min:35, porc:"2 mitades", k:321, p:30, c:15, g:17,
   ing:["1 zapallo italiano grande (o 2 chicos)","80 g de carne molida magra","1 tomate picado","1 lámina de queso gauda","Cebolla, ajo, orégano y sal"],
   pasos:["Corta el zapallo a lo largo y saca la pulpa con una cuchara.","Dora la carne con la cebolla, el ajo, el tomate y la pulpa picada.","Rellena los zapallos y pon el queso encima.","Hornea a 180 °C por 20 minutos."] },
 { n:"Sopa de verduras con pollo", cat:"Cena", e:"🍜", min:30, porc:"1 plato hondo", k:267, p:30, c:29, g:4,
   ing:["80 g de pollo desmenuzado","2 tazas de verduras (zanahoria, zapallo, apio, porotos verdes)","1/4 taza de fideos cabellos de ángel","Ajo, perejil y sal"],
   pasos:["Hierve las verduras picadas en 1 litro de agua con ajo y sal por 15 minutos.","Agrega el pollo y los fideos y cocina 5 minutos.","Sirve con perejil picado."] },
 { n:"Omelette de champiñones", cat:"Cena", e:"🍄", min:10, porc:"1 omelette", k:248, p:23, c:4, g:15,
   ing:["2 huevos y 1 clara","1 taza de champiñones laminados","1 lámina de queso gauda","Sal, pimienta y ciboulette"],
   pasos:["Saltea los champiñones en un sartén antiadherente hasta que suelten su agua.","Agrega los huevos batidos con sal y pimienta.","Pon el queso en la mitad, dobla y cocina 1 minuto más."] },
 { n:"Tacos de lechuga con carne", cat:"Cena", e:"🌮", min:15, porc:"4 tacos", k:295, p:27, c:9, g:17,
   ing:["100 g de carne molida magra","4 hojas grandes de lechuga","1/2 taza de pebre (tomate, cebolla, cilantro)","2 cucharadas de palta","Comino, ajo y sal"],
   pasos:["Dora la carne con comino, ajo y sal.","Usa las hojas de lechuga como tortillas.","Rellena con la carne, el pebre y la palta."] },
 { n:"Bolitas energéticas de avena y maní", cat:"Colación", e:"🟤", min:10, porc:"2 bolitas", k:144, p:4, c:21, g:5,
   ing:["20 g de avena","1/2 cucharada de mantequilla de maní","1 cucharadita de miel","Canela (opcional)"],
   pasos:["Mezcla todos los ingredientes en un bowl.","Forma 2 bolitas con las manos húmedas.","Refrigera 30 minutos antes de comer."] },
 { n:"Palitos de verduras con hummus", cat:"Colación", e:"🥕", min:10, porc:"1 porción", k:110, p:4, c:15, g:5,
   ing:["3 cucharadas de hummus (45 g)","1 taza de palitos de zanahoria y pepino"],
   pasos:["Corta la zanahoria y el pepino en bastones.","Sirve con el hummus para untar."] }
];
