/* Recetario saludable de WGYMNUTRI (10/2026). Recetas simples y generales
   (no son las de comidas-saludables.html: la dueña pidió un recetario
   aparte). Calorías y macros por porción, calculados con los valores de
   nutri-alimentos.js; son aproximados.
   k = kcal, p = proteína g, c = carbohidratos g, g = grasas g. */
window.NUTRI_RECETAS = [
 { n:"Avena proteica con plátano", cat:"Desayuno", e:"🥣", min:5, porc:"1 bowl", k:332, p:25, c:52, g:4,
   ing:["40 g de avena (1/2 taza)","200 ml de leche descremada","1/2 plátano en rodajas","1/2 scoop de proteína whey (15 g)","Canela a gusto"],
   pasos:["Calienta la leche con la avena 3 minutos, revolviendo.","Retira del fuego y deja enfriar 1 minuto.","Agrega la proteína y revuelve hasta que no queden grumos (si la pones hirviendo se corta).","Cubre con el plátano y la canela."] },
 { n:"Omelette de claras con espinaca y quesillo", cat:"Desayuno", e:"🍳", min:10, porc:"1 omelette + 1 pan integral", k:308, p:30, c:18, g:13,
   ing:["1 huevo entero y 3 claras","1/2 taza de espinaca","50 g de quesillo","1 cucharadita de aceite","1 rebanada de pan integral","Sal y pimienta"],
   pasos:["Bate el huevo con las claras, sal y pimienta.","Saltea la espinaca 1 minuto en el sartén con el aceite.","Vierte los huevos, cocina a fuego bajo y agrega el quesillo en la mitad.","Dobla el omelette y sirve con el pan tostado."] },
 { n:"Pan integral con palta y huevo", cat:"Desayuno", e:"🥑", min:10, porc:"2 rebanadas", k:260, p:14, c:27, g:11,
   ing:["2 rebanadas de pan integral","2 cucharadas de palta","1 huevo","Tomate en rodajas (opcional)","Sal y orégano"],
   pasos:["Cuece el huevo 9 minutos y pélalo.","Tuesta el pan.","Unta la palta, agrega el tomate y el huevo en láminas.","Termina con sal y orégano."] },
 { n:"Yogur proteico con frutillas y almendras", cat:"Colación", e:"🍓", min:3, porc:"1 pote", k:183, p:18, c:16, g:6,
   ing:["1 yogur proteico (160 g)","1/2 taza de frutillas picadas","10 g de almendras picadas"],
   pasos:["Sirve el yogur en un pote.","Agrega las frutillas y las almendras encima."] },
 { n:"Batido verde de proteína", cat:"Colación", e:"🥤", min:3, porc:"1 vaso grande", k:232, p:26, c:31, g:2,
   ing:["1 scoop de proteína whey (30 g)","1 plátano","1 taza de espinaca cruda","250 ml de agua fría o hielo"],
   pasos:["Pon todo en la licuadora.","Licúa 30 a 40 segundos hasta que quede liso.","Tómalo después de entrenar."] },
 { n:"Manzana con mantequilla de maní", cat:"Colación", e:"🍎", min:2, porc:"1 manzana", k:190, p:4, c:29, g:8,
   ing:["1 manzana","1 cucharada de mantequilla de maní","Canela (opcional)"],
   pasos:["Corta la manzana en gajos.","Úntalos con la mantequilla de maní y espolvorea canela."] },
 { n:"Bowl de pollo, arroz integral y verduras", cat:"Almuerzo", e:"🍗", min:25, porc:"1 bowl", k:477, p:45, c:50, g:11,
   ing:["120 g de pechuga de pollo","3/4 taza de arroz integral cocido","1 taza de brócoli","1/2 taza de zanahoria rallada","1 cucharadita de aceite de oliva","Ajo, comino, sal y limón"],
   pasos:["Condimenta el pollo con ajo, comino y sal, y cocínalo a la plancha 5 a 6 minutos por lado.","Cuece el brócoli al vapor 4 minutos.","Arma el bowl con el arroz, el pollo en tiras, el brócoli y la zanahoria.","Aliña con el aceite de oliva y limón."] },
 { n:"Ensalada de atún, garbanzos y tomate", cat:"Almuerzo", e:"🥗", min:10, porc:"1 plato grande", k:342, p:39, c:30, g:8,
   ing:["1 lata de atún en agua","1/2 taza de garbanzos cocidos","1 tomate","Lechuga a gusto","1 cucharadita de aceite de oliva","Limón, cebollín y sal"],
   pasos:["Escurre el atún y enjuaga los garbanzos.","Pica el tomate, la lechuga y el cebollín.","Mezcla todo en un bowl.","Aliña con aceite, limón y sal."] },
 { n:"Carne salteada con verduras y arroz", cat:"Almuerzo", e:"🥩", min:20, porc:"1 plato", k:411, p:38, c:36, g:12,
   ing:["120 g de posta en tiras","1 1/2 taza de pimentón, cebolla y porotos verdes","1/2 taza de arroz blanco cocido","1 cucharadita de aceite","Salsa de soya baja en sodio, ajo y jengibre"],
   pasos:["Calienta el sartén bien caliente con el aceite.","Saltea la carne 2 a 3 minutos y retírala.","Saltea las verduras 4 minutos con ajo y jengibre.","Devuelve la carne, agrega un chorrito de soya y sirve con el arroz."] },
 { n:"Lentejas con verduras", cat:"Almuerzo", e:"🍲", min:35, porc:"1 plato", k:310, p:19, c:49, g:6,
   ing:["1 taza de lentejas cocidas","1/2 zanahoria y 1/2 zapallo italiano en cubos","1/4 de cebolla y 1 diente de ajo","1 cucharadita de aceite","Comino, pimentón y sal"],
   pasos:["Sofríe la cebolla y el ajo en el aceite.","Agrega la zanahoria y el zapallo, y cocina 5 minutos.","Suma las lentejas, 1 taza de agua y los condimentos.","Cocina 15 minutos a fuego bajo hasta que espese."] },
 { n:"Salmón al horno con camote", cat:"Cena", e:"🐟", min:30, porc:"1 plato", k:398, p:31, c:34, g:16,
   ing:["120 g de salmón","1 camote mediano (150 g)","Ensalada de lechuga","Limón, eneldo, sal y pimienta"],
   pasos:["Precalienta el horno a 200 °C.","Corta el camote en bastones y hornéalo 15 minutos.","Agrega el salmón condimentado a la bandeja y hornea 12 minutos más.","Sirve con la ensalada y limón."] },
 { n:"Tortilla de zapallo italiano al horno", cat:"Cena", e:"🥚", min:25, porc:"1 porción", k:253, p:20, c:9, g:16,
   ing:["2 huevos","1 zapallo italiano rallado","1/4 de cebolla picada","1 lámina de queso gauda","Sal, pimienta y orégano"],
   pasos:["Precalienta el horno a 180 °C.","Bate los huevos y mezcla con el zapallo, la cebolla y los condimentos.","Vierte en un molde pequeño y pon el queso encima.","Hornea 18 a 20 minutos, hasta que esté firme."] },
 { n:"Wrap de pavo y verduras", cat:"Cena", e:"🌯", min:8, porc:"1 wrap", k:257, p:29, c:25, g:4,
   ing:["1 tortilla de trigo","80 g de pechuga de pavo","Lechuga y tomate","1 cucharada de yogur natural","Mostaza (opcional)"],
   pasos:["Calienta la tortilla 20 segundos en el sartén.","Unta el yogur y la mostaza.","Agrega el pavo, la lechuga y el tomate.","Enrolla apretando bien y corta por la mitad."] },
 { n:"Mousse de yogur y cacao", cat:"Postre", e:"🍫", min:5, porc:"1 pote", k:112, p:16, c:10, g:1,
   ing:["1 yogur proteico natural (160 g)","1 cucharadita de cacao amargo","Endulzante a gusto"],
   pasos:["Mezcla el yogur con el cacao y el endulzante.","Bate con un tenedor hasta que quede cremoso.","Enfría 10 minutos antes de comer."] },
 /* Agregadas el 10-10-2026 (la dueña pidió más recetas). */
 { n:"Huevos revueltos con tomate y pan pita", cat:"Desayuno", e:"🍅", min:8, porc:"2 huevos + 1 pita", k:320, p:19, c:36, g:11,
   ing:["2 huevos","1/2 tomate picado","1 pan pita integral","Sal, pimienta y cebollín"],
   pasos:["Calienta un sartén antiadherente y saltea el tomate 1 minuto.","Agrega los huevos batidos y revuelve a fuego bajo hasta que cuajen.","Calienta la pita y rellénala con los huevos.","Termina con cebollín picado."] },
 { n:"Panqueques de avena y plátano", cat:"Desayuno", e:"🥞", min:15, porc:"3 panqueques", k:344, p:16, c:55, g:8,
   ing:["40 g de avena","1 plátano maduro","1 huevo y 1 clara","Canela y 1 pizca de polvos de hornear"],
   pasos:["Licúa todos los ingredientes hasta tener una mezcla espesa.","Calienta un sartén antiadherente a fuego medio.","Pon 3 cucharadas de mezcla por panqueque y cocina 2 minutos por lado.","Sirve con canela o unas frutillas."] },
 { n:"Pudding de chía con frutillas", cat:"Desayuno", e:"🍮", min:5, porc:"1 vaso", k:191, p:11, c:24, g:7,
   ing:["2 cucharadas de chía (20 g)","200 ml de leche descremada","1/2 taza de frutillas","Endulzante y vainilla a gusto"],
   pasos:["Mezcla la chía con la leche, la vainilla y el endulzante.","Revuelve bien y deja en el refrigerador toda la noche (o mínimo 2 horas).","En la mañana agrega las frutillas picadas."] },
 { n:"Tostadas con quesillo y tomate", cat:"Once", e:"🍞", min:5, porc:"2 tostadas", k:217, p:15, c:30, g:4,
   ing:["2 rebanadas de pan integral","50 g de quesillo","1 tomate en rodajas","Orégano y sal"],
   pasos:["Tuesta el pan.","Pon el quesillo en láminas y el tomate encima.","Termina con orégano y una pizca de sal."] },
 { n:"Pan pita con pollo y palta", cat:"Once", e:"🥙", min:10, porc:"1 pita", k:345, p:31, c:36, g:9,
   ing:["1 pan pita integral","80 g de pollo cocido desmenuzado","2 cucharadas de palta","Lechuga y tomate"],
   pasos:["Calienta la pita y ábrela por un costado.","Unta la palta por dentro.","Rellena con el pollo, la lechuga y el tomate."] },
 { n:"Pollo al horno con papas y ensalada chilena", cat:"Almuerzo", e:"🍗", min:45, porc:"1 plato", k:453, p:50, c:38, g:10,
   ing:["150 g de pechuga o trutro sin piel","1 papa mediana en gajos","1 plato de ensalada chilena (tomate y cebolla)","1 cucharadita de aceite","Ajo, merkén, orégano y sal"],
   pasos:["Precalienta el horno a 200 °C.","Condimenta el pollo y las papas con ajo, merkén, orégano, sal y el aceite.","Hornea todo junto 35 a 40 minutos, dando vuelta a la mitad.","Sirve con la ensalada chilena."] },
 { n:"Cazuela de pollo liviana", cat:"Almuerzo", e:"🍲", min:40, porc:"1 plato", k:372, p:43, c:40, g:6,
   ing:["120 g de pechuga de pollo","1/2 papa","1 trozo de zapallo","1/2 choclo (o 1/2 taza de granos)","1/2 taza de porotos verdes","Cilantro, ajo, comino y sal"],
   pasos:["Hierve el pollo en 1 litro de agua con ajo, comino y sal por 15 minutos.","Agrega la papa y el zapallo y cocina 10 minutos.","Suma el choclo y los porotos verdes y cocina 8 minutos más.","Sirve con cilantro picado."] },
 { n:"Quínoa con verduras y pollo", cat:"Almuerzo", e:"🥘", min:25, porc:"1 plato", k:412, p:38, c:37, g:11,
   ing:["3/4 taza de quínoa cocida","100 g de pollo en cubos","1 taza de pimentón y zapallo italiano picados","1 cucharadita de aceite","Ajo, cúrcuma y sal"],
   pasos:["Lava bien la quínoa y cuécela 15 minutos en el doble de agua.","Saltea el pollo con el aceite y el ajo hasta dorar.","Agrega las verduras y la cúrcuma y saltea 4 minutos.","Mezcla con la quínoa y ajusta la sal."] },
 { n:"Tallarines integrales con atún y tomate", cat:"Almuerzo", e:"🍝", min:20, porc:"1 plato", k:384, p:38, c:45, g:7,
   ing:["1 taza de tallarines integrales cocidos","1 lata de atún en agua","1/2 taza de salsa de tomate casera","1 cucharadita de aceite de oliva","Ajo y albahaca"],
   pasos:["Cuece los tallarines según el paquete.","Sofríe el ajo en el aceite, agrega la salsa de tomate y cocina 5 minutos.","Suma el atún escurrido y calienta 1 minuto.","Mezcla con los tallarines y termina con albahaca."] },
 { n:"Merluza a la plancha con puré de zapallo", cat:"Cena", e:"🐠", min:25, porc:"1 plato", k:283, p:35, c:30, g:3,
   ing:["150 g de merluza o reineta","1 taza de zapallo cocido","1/2 papa cocida","50 ml de leche descremada","Limón, ajo, sal y nuez moscada"],
   pasos:["Cuece el zapallo y la papa hasta que estén blandos y muélelos con la leche, sal y nuez moscada.","Condimenta el pescado con limón, ajo y sal.","Cocínalo en un sartén antiadherente 3 a 4 minutos por lado.","Sirve sobre el puré."] },
 { n:"Ensalada César liviana con pollo", cat:"Cena", e:"🥬", min:15, porc:"1 plato grande", k:330, p:44, c:15, g:9,
   ing:["120 g de pechuga de pollo a la plancha","2 tazas de lechuga","2 cucharadas de yogur natural con limón y ajo (salsa)","10 g de queso parmesano","15 g de crutones"],
   pasos:["Cocina el pollo a la plancha y córtalo en tiras.","Mezcla el yogur con limón, ajo y una pizca de sal para la salsa.","Arma la ensalada con la lechuga, el pollo y los crutones.","Aliña con la salsa y espolvorea el parmesano."] },
 { n:"Hamburguesa casera de pavo con ensalada", cat:"Cena", e:"🍔", min:20, porc:"1 hamburguesa", k:268, p:29, c:10, g:13,
   ing:["120 g de pavo molido","Lechuga y tomate","2 cucharadas de palta","Ajo, cebolla en polvo, sal y pimienta"],
   pasos:["Mezcla el pavo con los condimentos y forma una hamburguesa.","Cocínala en un sartén antiadherente 5 minutos por lado.","Sírvela sobre la lechuga y el tomate, con la palta encima."] },
 { n:"Porotos verdes salteados con huevo", cat:"Cena", e:"🫛", min:15, porc:"1 plato", k:250, p:16, c:16, g:15,
   ing:["1 1/2 taza de porotos verdes","2 huevos","1 cucharadita de aceite","Ajo, sal y pimienta"],
   pasos:["Cuece los porotos verdes 5 minutos y escúrrelos.","Saltéalos con el aceite y el ajo 3 minutos.","Agrega los huevos batidos y revuelve hasta que cuajen."] },
 { n:"Garbanzos asados crocantes", cat:"Colación", e:"🫘", min:30, porc:"1/2 taza", k:155, p:7, c:23, g:4,
   ing:["1/2 taza de garbanzos cocidos","1/2 cucharadita de aceite","Pimentón, comino y sal"],
   pasos:["Seca muy bien los garbanzos con papel absorbente.","Mézclalos con el aceite y los condimentos.","Hornea a 200 °C por 25 minutos, moviendo la bandeja a la mitad, hasta que estén crocantes."] },
 { n:"Huevos duros con palta", cat:"Colación", e:"🥚", min:12, porc:"2 huevos", k:192, p:13, c:3, g:14,
   ing:["2 huevos","2 cucharadas de palta","Sal y merkén"],
   pasos:["Cuece los huevos 9 minutos y pélalos.","Córtalos por la mitad y pon la palta encima.","Termina con sal y merkén."] },
 { n:"Batido de frutilla y avena", cat:"Colación", e:"🍹", min:3, porc:"1 vaso grande", k:271, p:24, c:39, g:3,
   ing:["250 ml de leche descremada","1 taza de frutillas","20 g de avena","1/2 scoop de proteína whey (15 g)"],
   pasos:["Pon todo en la licuadora.","Licúa hasta que quede cremoso.","Sirve frío."] },
 { n:"Helado de plátano y cacao", cat:"Postre", e:"🍨", min:5, porc:"1 pote", k:117, p:2, c:29, g:1,
   ing:["1 plátano congelado en rodajas","1 cucharadita de cacao amargo"],
   pasos:["Congela el plátano en rodajas mínimo 3 horas.","Muélelo en la licuadora o procesadora con el cacao hasta que quede como helado.","Cómelo al tiro."] },
 { n:"Manzana asada con canela y yogur", cat:"Postre", e:"🍏", min:20, porc:"1 manzana", k:150, p:6, c:32, g:1,
   ing:["1 manzana","Canela a gusto","1 yogur natural light (125 g)"],
   pasos:["Corta la manzana en cubos y espolvorea canela.","Cocínala en el microondas 3 a 4 minutos (o al horno 15 minutos).","Sirve tibia con el yogur encima."] },
 /* Agregadas el 10-10-2026, segunda tanda (la dueña pidió llegar a 50). */
 { n:"Avena remojada con manzana y canela", cat:"Desayuno", e:"🍎", min:5, porc:"1 frasco", k:288, p:14, c:52, g:3,
   ing:["40 g de avena","1 yogur natural light (125 g)","100 ml de leche descremada","1/2 manzana picada","Canela a gusto"],
   pasos:["Mezcla en un frasco la avena, el yogur y la leche.","Agrega la manzana y la canela.","Tapa y deja en el refrigerador toda la noche. En la mañana está lista."] },
 { n:"Wrap de huevo y espinaca", cat:"Desayuno", e:"🌯", min:10, porc:"1 wrap", k:284, p:18, c:24, g:13,
   ing:["1 tortilla de trigo","2 huevos","1/2 taza de espinaca","Sal y pimienta"],
   pasos:["Saltea la espinaca 1 minuto en un sartén antiadherente.","Agrega los huevos batidos y revuelve hasta que cuajen.","Calienta la tortilla, rellena y enrolla."] },
 { n:"Tostadas con mantequilla de maní y plátano", cat:"Desayuno", e:"🍌", min:5, porc:"2 tostadas", k:287, p:11, c:41, g:10,
   ing:["2 rebanadas de pan integral","1 cucharada de mantequilla de maní","1/2 plátano en rodajas","Canela (opcional)"],
   pasos:["Tuesta el pan.","Unta la mantequilla de maní.","Pon el plátano encima y espolvorea canela."] },
 { n:"Sándwich de pavo y quesillo", cat:"Once", e:"🥪", min:5, porc:"1 sándwich", k:255, p:22, c:30, g:5,
   ing:["2 rebanadas de pan integral","2 láminas de jamón de pavo","50 g de quesillo","Lechuga y tomate"],
   pasos:["Tuesta el pan si te gusta crujiente.","Arma el sándwich con el pavo, el quesillo, la lechuga y el tomate."] },
 { n:"Media marraqueta con huevo y tomate", cat:"Once", e:"🥖", min:8, porc:"1/2 marraqueta", k:218, p:11, c:31, g:6,
   ing:["1/2 marraqueta","1 huevo","1/2 tomate en rodajas","Sal y orégano"],
   pasos:["Revuelve el huevo en un sartén antiadherente, sin aceite.","Tuesta la media marraqueta.","Pon el tomate y el huevo encima, con sal y orégano."] },
 { n:"Pescado al jugo con verduras", cat:"Almuerzo", e:"🐟", min:25, porc:"1 plato", k:343, p:34, c:33, g:8,
   ing:["150 g de reineta o merluza","1 taza de cebolla, pimentón y tomate en pluma","1/2 taza de arroz integral cocido","1 cucharadita de aceite","Ajo, orégano, limón y sal"],
   pasos:["Sofríe la cebolla, el pimentón y el ajo en el aceite 4 minutos.","Agrega el tomate y un chorrito de agua.","Pon el pescado encima, tapa y cocina 8 a 10 minutos a fuego bajo.","Sirve con el arroz y limón."] },
 { n:"Charquicán liviano", cat:"Almuerzo", e:"🥔", min:35, porc:"1 plato", k:363, p:28, c:39, g:12,
   ing:["90 g de carne molida magra","1/2 papa","1 taza de zapallo","1/4 taza de choclo","1/2 taza de porotos verdes","Cebolla, ajo, comino y sal"],
   pasos:["Dora la carne con la cebolla y el ajo, sin aceite extra.","Agrega la papa, el zapallo y 1/2 taza de agua, y cocina 15 minutos.","Suma el choclo y los porotos verdes y cocina 5 minutos más.","Muele un poco con un tenedor y sirve. Puedes agregar un huevo a la plancha."] },
 { n:"Porotos con zapallo", cat:"Almuerzo", e:"🫘", min:30, porc:"1 plato", k:244, p:13, c:38, g:5,
   ing:["3/4 taza de porotos cocidos","1/2 taza de zapallo en cubos","1/4 de cebolla","1 cucharadita de aceite","Pimentón, orégano y sal"],
   pasos:["Sofríe la cebolla en el aceite con el pimentón.","Agrega el zapallo y los porotos con 1 taza de agua.","Cocina 15 minutos hasta que el zapallo se deshaga y espese.","Acompaña con ensalada para un plato completo."] },
 { n:"Pechuga rellena de espinaca y quesillo", cat:"Almuerzo", e:"🍗", min:35, porc:"1 pechuga + 1 papa", k:453, p:59, c:35, g:8,
   ing:["150 g de pechuga de pollo","1/2 taza de espinaca","50 g de quesillo","1 papa cocida","Ajo, sal y pimienta"],
   pasos:["Abre la pechuga por la mitad como un libro.","Rellena con la espinaca y el quesillo, y ciérrala con un palito.","Hornea a 200 °C por 25 minutos.","Sirve con la papa cocida."] },
 { n:"Arroz chaufa liviano de pollo", cat:"Almuerzo", e:"🍚", min:20, porc:"1 plato", k:459, p:42, c:38, g:14,
   ing:["3/4 taza de arroz integral cocido (frío)","100 g de pollo en cubos","1 huevo","Cebollín y pimentón picados","1 cucharadita de aceite","Salsa de soya baja en sodio y jengibre"],
   pasos:["Saltea el pollo con el aceite hasta dorar.","Agrega el huevo batido y revuelve.","Suma el arroz, el cebollín, el pimentón y el jengibre.","Termina con un chorrito de soya y saltea 2 minutos más."] },
 { n:"Ensalada de lentejas con queso fresco", cat:"Almuerzo", e:"🥗", min:10, porc:"1 plato", k:410, p:28, c:51, g:13,
   ing:["1 taza de lentejas cocidas","Tomate, pepino y cebolla morada picados","50 g de queso fresco en cubos","1 cucharadita de aceite de oliva","Limón, cilantro y sal"],
   pasos:["Enjuaga y escurre las lentejas.","Mézclalas con las verduras picadas.","Agrega el queso fresco.","Aliña con aceite, limón, cilantro y sal."] },
 { n:"Palta reina liviana", cat:"Cena", e:"🥑", min:10, porc:"1/2 palta", k:197, p:17, c:8, g:11,
   ing:["1/2 palta","1/2 lata de atún en agua","1 cucharada de yogur natural","Lechuga, limón y sal"],
   pasos:["Mezcla el atún con el yogur, limón y sal.","Rellena la media palta con la mezcla.","Sirve sobre hojas de lechuga."] },
 { n:"Zapallo italiano relleno", cat:"Cena", e:"🥒", min:35, porc:"2 mitades", k:321, p:30, c:15, g:17,
   ing:["1 zapallo italiano grande (o 2 chicos)","80 g de carne molida magra","1 tomate picado","1 lámina de queso gauda","Cebolla, ajo, orégano y sal"],
   pasos:["Corta el zapallo a lo largo y saca la pulpa con una cuchara.","Dora la carne con la cebolla, el ajo, el tomate y la pulpa picada.","Rellena los zapallos y pon el queso encima.","Hornea a 180 °C por 20 minutos."] },
 { n:"Sopa de verduras con pollo", cat:"Cena", e:"🍜", min:30, porc:"1 plato hondo", k:267, p:30, c:29, g:4,
   ing:["80 g de pollo desmenuzado","2 tazas de verduras (zanahoria, zapallo, apio, porotos verdes)","1/4 taza de fideos cabellos de ángel","Ajo, perejil y sal"],
   pasos:["Hierve las verduras picadas en 1 litro de agua con ajo y sal por 15 minutos.","Agrega el pollo y los fideos y cocina 5 minutos.","Sirve con perejil picado."] },
 { n:"Omelette de champiñones", cat:"Cena", e:"🍄", min:10, porc:"1 omelette", k:248, p:23, c:4, g:15,
   ing:["2 huevos y 1 clara","1 taza de champiñones laminados","1 lámina de queso gauda","Sal, pimienta y ciboulette"],
   pasos:["Saltea los champiñones en un sartén antiadherente hasta que suelten su agua.","Agrega los huevos batidos con sal y pimienta.","Pon el queso en la mitad, dobla y cocina 1 minuto más."] },
 { n:"Tacos de lechuga con carne", cat:"Cena", e:"🌮", min:15, porc:"4 tacos", k:295, p:27, c:9, g:17,
   ing:["100 g de carne molida magra","4 hojas grandes de lechuga","1/2 taza de pebre (tomate, cebolla, cilantro)","2 cucharadas de palta","Comino, ajo y sal"],
   pasos:["Dora la carne con comino, ajo y sal.","Usa las hojas de lechuga como tortillas.","Rellena con la carne, el pebre y la palta."] },
 { n:"Bolitas energéticas de avena y maní", cat:"Colación", e:"🟤", min:10, porc:"2 bolitas", k:144, p:4, c:21, g:5,
   ing:["20 g de avena","1/2 cucharada de mantequilla de maní","1 cucharadita de miel","Canela (opcional)"],
   pasos:["Mezcla todos los ingredientes en un bowl.","Forma 2 bolitas con las manos húmedas.","Refrigera 30 minutos antes de comer."] },
 { n:"Palitos de verduras con hummus", cat:"Colación", e:"🥕", min:10, porc:"1 porción", k:110, p:4, c:15, g:5,
   ing:["3 cucharadas de hummus (45 g)","1 taza de palitos de zanahoria y pepino"],
   pasos:["Corta la zanahoria y el pepino en bastones.","Sirve con el hummus para untar."] },
 /* 30 postres saludables (10-10-2026, la dueña: "hay muy pocos"). */
 { n:"Brownie de avena y cacao", cat:"Postre", e:"🍫", min:30, porc:"1 cuadrado", k:173, p:7, c:25, g:5,
   ing:["20 g de avena", "1/4 de plátano maduro", "1/2 huevo", "1 cucharada de cacao amargo", "Endulzante y polvos de hornear"],
   pasos:["Precalienta el horno a 180 °C.", "Muele la avena y mézclala con el plátano molido, el huevo, el cacao y el endulzante.", "Vierte en un molde chico y hornea 20 minutos.", "Deja enfriar y corta en cuadrados (la receta x4 rinde 4 cuadrados)."] },
 { n:"Mousse de chocolate y palta", cat:"Postre", e:"🥑", min:10, porc:"1 pote", k:159, p:10, c:15, g:7,
   ing:["1/4 de palta madura", "1 cucharada de cacao amargo", "75 g de yogur griego light", "1 cucharadita de miel"],
   pasos:["Muele todo en la licuadora o con un tenedor hasta que quede cremoso.", "Sirve en un pote y enfría 20 minutos.", "No se siente el sabor a palta: queda como mousse de chocolate."] },
 { n:"Cheesecake proteico en vaso", cat:"Postre", e:"🍰", min:10, porc:"1 vaso", k:179, p:17, c:20, g:4,
   ing:["50 g de quesillo", "75 g de yogur griego light", "15 g de avena", "1/2 taza de frutillas", "Endulzante y ralladura de limón"],
   pasos:["Pon la avena tostada en el fondo del vaso.", "Muele el quesillo con el yogur, el endulzante y el limón.", "Agrega la crema sobre la avena.", "Cubre con frutillas picadas y enfría."] },
 { n:"Helado de frutilla y yogur", cat:"Postre", e:"🍓", min:5, porc:"1 pote", k:151, p:16, c:20, g:1,
   ing:["1 taza de frutillas congeladas", "1 yogur proteico (160 g)", "Endulzante a gusto"],
   pasos:["Pon las frutillas congeladas y el yogur en la licuadora.", "Muele hasta que quede como helado suave.", "Cómelo al tiro o congela 30 minutos para más firme."] },
 { n:"Paletas de yogur y arándanos", cat:"Postre", e:"🍦", min:5, porc:"2 paletas", k:99, p:6, c:18, g:0,
   ing:["1 yogur natural light (125 g)", "1/2 taza de arándanos", "Endulzante a gusto"],
   pasos:["Mezcla el yogur con el endulzante.", "Reparte en moldes de paleta con los arándanos.", "Congela 4 horas."] },
 { n:"Galletas de avena y plátano", cat:"Postre", e:"🍪", min:20, porc:"3 galletas", k:159, p:3, c:33, g:2,
   ing:["40 g de avena (rinde 6 galletas)", "1 plátano maduro", "1 cucharada de pasas", "Canela"],
   pasos:["Precalienta el horno a 180 °C.", "Muele el plátano y mézclalo con la avena, las pasas y la canela.", "Forma 6 galletas en una bandeja con papel.", "Hornea 15 minutos. Una porción son 3 galletas."] },
 { n:"Trufas de dátiles y cacao", cat:"Postre", e:"🟤", min:15, porc:"3 trufas", k:182, p:4, c:23, g:8,
   ing:["3 dátiles sin cuesco", "1 cucharadita de cacao amargo", "10 g de almendras", "Coco rallado para cubrir"],
   pasos:["Muele los dátiles con las almendras y el cacao hasta formar una pasta.", "Forma 3 bolitas.", "Pásalas por coco rallado y refrigera."] },
 { n:"Manzana al horno con avena", cat:"Postre", e:"🍎", min:25, porc:"1 manzana", k:202, p:3, c:44, g:2,
   ing:["1 manzana", "20 g de avena", "1 cucharadita de miel", "Canela"],
   pasos:["Precalienta el horno a 180 °C.", "Saca el centro de la manzana.", "Rellena con la avena, la miel y la canela.", "Hornea 20 minutos hasta que esté blanda."] },
 { n:"Pera cocida con canela y yogur", cat:"Postre", e:"🍐", min:15, porc:"1 pera", k:164, p:6, c:34, g:0,
   ing:["1 pera", "1 yogur natural light (125 g)", "Canela y clavo de olor"],
   pasos:["Pela la pera y cuécela en agua con canela y clavo 10 minutos.", "Deja entibiar.", "Sirve con el yogur encima."] },
 { n:"Gelatina con frutas y yogur", cat:"Postre", e:"🍮", min:10, porc:"1 pote", k:73, p:5, c:12, g:0,
   ing:["1 pote de gelatina sin azúcar", "1/2 taza de frutilla y kiwi picados", "1/2 yogur natural light"],
   pasos:["Prepara la gelatina sin azúcar y agrega la fruta antes de que cuaje.", "Refrigera 2 horas.", "Sirve con el yogur encima."] },
 { n:"Panqueque proteico con frutillas", cat:"Postre", e:"🥞", min:10, porc:"2 panqueques", k:249, p:25, c:21, g:7,
   ing:["1 huevo y 1 clara", "15 g de proteína whey", "20 g de avena", "1/2 taza de frutillas"],
   pasos:["Licúa el huevo, la clara, la proteína y la avena.", "Cocina 2 panqueques en un sartén antiadherente.", "Sirve con las frutillas picadas."] },
 { n:"Flan de leche liviano", cat:"Postre", e:"🍮", min:40, porc:"1 pote", k:123, p:12, c:8, g:5,
   ing:["150 ml de leche descremada", "1 huevo", "Endulzante y vainilla"],
   pasos:["Bate la leche con el huevo, el endulzante y la vainilla.", "Vierte en un pote apto para horno.", "Hornea a baño maría a 170 °C por 30 minutos.", "Enfría antes de comer."] },
 { n:"Arroz con leche liviano", cat:"Postre", e:"🍚", min:30, porc:"1 pote", k:120, p:7, c:22, g:0,
   ing:["1/3 taza de arroz cocido", "150 ml de leche descremada", "Endulzante, canela y cáscara de limón"],
   pasos:["Cocina el arroz con la leche, la canela y la cáscara de limón a fuego bajo por 15 minutos.", "Revuelve seguido para que no se pegue.", "Endulza al final y sirve con canela."] },
 { n:"Leche asada liviana", cat:"Postre", e:"🥛", min:40, porc:"1 pote", k:138, p:15, c:8, g:5,
   ing:["150 ml de leche descremada", "1 huevo y 1 clara", "Endulzante y vainilla"],
   pasos:["Bate todos los ingredientes.", "Vierte en un pote apto para horno.", "Hornea a 180 °C por 30 minutos hasta que se dore arriba."] },
 { n:"Mousse de maracuyá", cat:"Postre", e:"💛", min:10, porc:"1 pote", k:137, p:17, c:15, g:1,
   ing:["150 g de yogur griego light", "Pulpa de 2 maracuyás", "1/2 sobre de gelatina sin sabor", "Endulzante"],
   pasos:["Disuelve la gelatina en 2 cucharadas de agua caliente.", "Mezcla el yogur con la pulpa de maracuyá, el endulzante y la gelatina.", "Refrigera 2 horas."] },
 { n:"Bowl de frutos rojos", cat:"Postre", e:"🫐", min:5, porc:"1 bowl", k:250, p:11, c:44, g:4,
   ing:["1 taza de frutos rojos congelados", "1/2 plátano", "1/2 yogur proteico", "15 g de granola"],
   pasos:["Licúa los frutos rojos con el plátano y el yogur hasta que quede espeso.", "Sirve en un bowl.", "Cubre con la granola."] },
 { n:"Mug cake de chocolate proteico", cat:"Postre", e:"☕", min:5, porc:"1 taza", k:193, p:20, c:21, g:3,
   ing:["15 g de proteína whey", "20 g de avena molida", "1 cucharada de cacao amargo", "1 clara", "30 ml de leche descremada", "1 pizca de polvos de hornear"],
   pasos:["Mezcla todo en una taza grande.", "Cocina en el microondas 60 a 90 segundos.", "Deja reposar 1 minuto antes de comer."] },
 { n:"Plátano con chocolate amargo y maní", cat:"Postre", e:"🍌", min:5, porc:"1 plátano", k:239, p:5, c:33, g:10,
   ing:["1 plátano", "10 g de chocolate amargo 70 %", "10 g de maní picado"],
   pasos:["Derrite el chocolate en el microondas en intervalos de 15 segundos.", "Corta el plátano en rodajas.", "Baña con el chocolate y espolvorea el maní."] },
 { n:"Frutillas con chocolate amargo", cat:"Postre", e:"🍓", min:10, porc:"1 taza", k:145, p:2, c:18, g:7,
   ing:["1 taza de frutillas", "15 g de chocolate amargo 70 %"],
   pasos:["Derrite el chocolate.", "Baña la punta de cada frutilla.", "Refrigera 10 minutos hasta que endurezca."] },
 { n:"Compota de manzana sin azúcar", cat:"Postre", e:"🍏", min:15, porc:"1 pote", k:105, p:0, c:25, g:0,
   ing:["1 manzana", "Canela y clavo de olor", "1/4 taza de agua"],
   pasos:["Pela y pica la manzana.", "Cocínala con el agua, la canela y el clavo 10 minutos.", "Muele un poco y sirve tibia o fría."] },
 { n:"Sorbete de mango", cat:"Postre", e:"🥭", min:5, porc:"1 pote", k:111, p:1, c:25, g:1,
   ing:["1 taza de mango congelado", "Jugo de 1/2 limón", "Hojas de menta (opcional)"],
   pasos:["Muele el mango congelado con el limón.", "Sirve al tiro como sorbete.", "Decora con menta."] },
 { n:"Helado proteico de chocolate y plátano", cat:"Postre", e:"🍨", min:5, porc:"1 pote", k:212, p:16, c:32, g:2,
   ing:["1 plátano congelado", "15 g de proteína whey de chocolate o vainilla", "1 cucharadita de cacao amargo", "50 ml de leche descremada"],
   pasos:["Muele todo en la licuadora hasta que quede cremoso.", "Cómelo al tiro."] },
 { n:"Pudding de chía y cacao", cat:"Postre", e:"🍫", min:5, porc:"1 vaso", k:202, p:12, c:22, g:7,
   ing:["2 cucharadas de chía (20 g)", "200 ml de leche descremada", "1 cucharada de cacao amargo", "Endulzante"],
   pasos:["Mezcla todos los ingredientes.", "Revuelve bien y refrigera mínimo 2 horas.", "Revuelve de nuevo antes de servir."] },
 { n:"Muffin de avena y arándanos", cat:"Postre", e:"🧁", min:25, porc:"1 muffin", k:159, p:6, c:27, g:3,
   ing:["25 g de avena molida", "1/4 de huevo batido", "30 g de yogur light", "1/4 taza de arándanos", "1/2 cucharadita de miel y polvos de hornear"],
   pasos:["Precalienta el horno a 180 °C.", "Mezcla la avena, el huevo, el yogur, la miel y los polvos de hornear.", "Agrega los arándanos y vierte en un molde de muffin.", "Hornea 18 a 20 minutos."] },
 { n:"Barritas caseras de avena y maní", cat:"Postre", e:"🥜", min:15, porc:"1 barrita", k:149, p:4, c:21, g:5,
   ing:["20 g de avena", "1/2 cucharada de mantequilla de maní", "1 cucharadita de miel"],
   pasos:["Tibia la mantequilla de maní con la miel.", "Mezcla con la avena.", "Aprieta en un molde, refrigera 1 hora y corta en barritas."] },
 { n:"Mini cheesecake de ricotta y limón", cat:"Postre", e:"🍋", min:30, porc:"1 unidad", k:156, p:11, c:9, g:8,
   ing:["60 g de ricotta", "1 clara", "10 g de avena", "Ralladura de limón y endulzante"],
   pasos:["Precalienta el horno a 170 °C.", "Pon la avena en el fondo de un molde de muffin.", "Bate la ricotta con la clara, el limón y el endulzante y vierte encima.", "Hornea 20 minutos y enfría."] },
 { n:"Tiramisú liviano en vaso", cat:"Postre", e:"☕", min:10, porc:"1 vaso", k:224, p:18, c:29, g:4,
   ing:["150 g de yogur griego light", "2 bizcochos o 1 galleta de vino", "1/2 taza de café frío", "1 cucharadita de cacao amargo", "Endulzante"],
   pasos:["Moja los bizcochos en el café y ponlos en el fondo del vaso.", "Endulza el yogur y ponlo encima.", "Espolvorea el cacao y refrigera 30 minutos."] },
 { n:"Durazno a la plancha con yogur", cat:"Postre", e:"🍑", min:10, porc:"1 durazno", k:133, p:9, c:23, g:1,
   ing:["1 durazno en mitades", "75 g de yogur griego light", "1 cucharadita de miel", "Canela"],
   pasos:["Dora el durazno en un sartén antiadherente 2 minutos por lado.", "Sirve con el yogur.", "Termina con la miel y la canela."] },
 { n:"Macedonia de kiwi y naranja con menta", cat:"Postre", e:"🥝", min:5, porc:"1 pote", k:129, p:2, c:29, g:1,
   ing:["1 kiwi", "1 naranja", "Hojas de menta"],
   pasos:["Pela y pica el kiwi y la naranja.", "Mezcla con la menta picada.", "Sirve fría."] },
 { n:"Bocaditos helados de yogur y frutilla", cat:"Postre", e:"🍧", min:10, porc:"1 porción", k:184, p:16, c:18, g:5,
   ing:["1 yogur proteico (160 g)", "1/2 taza de frutillas picadas", "10 g de chocolate amargo 70 %"],
   pasos:["Mezcla el yogur con las frutillas.", "Pon cucharadas en una bandeja con papel y congela 2 horas.", "Baña con el chocolate derretido y vuelve a congelar 10 minutos."] },
 /* Más onces y colaciones (10-10-2026, la dueña: "hay muy pocas"). */
 { n:"Pan integral con palta y tomate", cat:"Once", e:"🥑", min:5, porc:"2 rebanadas", k:207, p:8, c:29, g:6,
   ing:["2 rebanadas de pan integral", "2 cucharadas de palta", "1/2 tomate en rodajas", "Sal y orégano"],
   pasos:["Tuesta el pan.", "Unta la palta.", "Pon el tomate encima con sal y orégano."] },
 { n:"Sándwich de atún y palta", cat:"Once", e:"🥪", min:5, porc:"1 sándwich", k:259, p:22, c:27, g:7,
   ing:["2 rebanadas de pan integral", "1/2 lata de atún en agua", "2 cucharadas de palta", "Lechuga y limón"],
   pasos:["Mezcla el atún escurrido con limón.", "Unta la palta en el pan.", "Arma el sándwich con el atún y la lechuga."] },
 { n:"Pan pita con huevo y quesillo", cat:"Once", e:"🥙", min:8, porc:"1 pita", k:292, p:19, c:35, g:8,
   ing:["1 pan pita integral", "1 huevo", "50 g de quesillo", "Tomate y orégano"],
   pasos:["Revuelve el huevo en un sartén antiadherente.", "Calienta la pita y ábrela.", "Rellena con el huevo, el quesillo y el tomate."] },
 { n:"Tostadas con ricotta y frutillas", cat:"Once", e:"🍓", min:5, porc:"2 tostadas", k:221, p:11, c:31, g:6,
   ing:["2 rebanadas de pan integral", "30 g de ricotta", "1/2 taza de frutillas", "Canela"],
   pasos:["Tuesta el pan.", "Unta la ricotta.", "Cubre con las frutillas en láminas y canela."] },
 { n:"Huevos revueltos con pan integral", cat:"Once", e:"🍳", min:8, porc:"2 huevos + 1 pan", k:224, p:17, c:15, g:11,
   ing:["2 huevos", "1 rebanada de pan integral", "1/2 tomate", "Sal y cebollín"],
   pasos:["Revuelve los huevos con el tomate picado en un sartén antiadherente.", "Tuesta el pan.", "Sirve con cebollín."] },
 { n:"Té con leche y tostadas con mermelada", cat:"Once", e:"☕", min:5, porc:"1 taza + 2 tostadas", k:195, p:11, c:33, g:2,
   ing:["1 taza de té con 100 ml de leche descremada", "2 rebanadas de pan integral", "1 cucharada de mermelada sin azúcar"],
   pasos:["Prepara el té con la leche, sin azúcar o con endulzante.", "Tuesta el pan.", "Unta la mermelada sin azúcar."] },
 { n:"Yogur con avena y plátano", cat:"Once", e:"🥣", min:3, porc:"1 pote", k:186, p:9, c:34, g:2,
   ing:["1 yogur natural light (125 g)", "20 g de avena", "1/2 plátano", "Canela"],
   pasos:["Sirve el yogur en un pote.", "Agrega la avena y el plátano en rodajas.", "Termina con canela."] },
 { n:"Wrap de pollo y verduras", cat:"Once", e:"🌯", min:8, porc:"1 wrap", k:234, p:22, c:24, g:5,
   ing:["1 tortilla de trigo", "60 g de pollo cocido", "Lechuga, tomate y zanahoria rallada", "Mostaza o yogur"],
   pasos:["Calienta la tortilla.", "Unta la mostaza o el yogur.", "Rellena con el pollo y las verduras y enrolla."] },
 { n:"Choclo con queso fresco", cat:"Once", e:"🌽", min:5, porc:"1 pote", k:146, p:8, c:17, g:5,
   ing:["1/2 taza de choclo en granos", "30 g de queso fresco en cubos", "Tomate picado y albahaca"],
   pasos:["Calienta el choclo.", "Mezcla con el queso fresco y el tomate.", "Termina con albahaca."] },
 { n:"Panqueques de avena con quesillo", cat:"Once", e:"🥞", min:12, porc:"2 panqueques", k:234, p:17, c:22, g:9,
   ing:["30 g de avena", "1 huevo", "50 g de quesillo", "Sal o canela, a gusto"],
   pasos:["Licúa la avena con el huevo y 2 cucharadas de agua.", "Cocina 2 panqueques en un sartén antiadherente.", "Rellena con el quesillo."] },
 { n:"Sopaipillas al horno", cat:"Once", e:"🟠", min:30, porc:"2 unidades", k:190, p:4, c:32, g:5,
   ing:["40 g de harina (rinde 2)", "40 g de zapallo cocido y molido", "1 cucharadita de aceite", "Sal y polvos de hornear"],
   pasos:["Mezcla el zapallo con la harina, el aceite, la sal y los polvos de hornear.", "Uslerea y corta 2 círculos.", "Pincha con tenedor y hornea a 200 °C por 15 a 18 minutos."] },
 { n:"Tortilla de espinaca en pan integral", cat:"Once", e:"🥬", min:10, porc:"1 sándwich abierto", k:184, p:18, c:14, g:6,
   ing:["1 huevo y 2 claras", "1/2 taza de espinaca", "1 rebanada de pan integral", "Sal y pimienta"],
   pasos:["Saltea la espinaca y agrega los huevos batidos.", "Cocina como tortilla, por los dos lados.", "Sírvela sobre el pan tostado."] },
 { n:"Queque de avena y plátano", cat:"Once", e:"🍰", min:40, porc:"1 trozo", k:150, p:6, c:25, g:3,
   ing:["25 g de avena molida", "1/4 de plátano maduro", "1/4 de huevo", "20 g de yogur natural", "Canela y polvos de hornear (multiplica por 6 para un queque)"],
   pasos:["Mezcla todos los ingredientes.", "Vierte en un molde de queque.", "Hornea a 180 °C por 30 a 35 minutos."] },
 { n:"Ensalada de frutas con yogur griego", cat:"Once", e:"🍇", min:8, porc:"1 pote", k:142, p:11, c:23, g:1,
   ing:["1 taza de frutas picadas (manzana, naranja, kiwi)", "100 g de yogur griego light", "Menta"],
   pasos:["Pica las frutas.", "Sírvelas con el yogur encima.", "Decora con menta."] },
 { n:"Pan integral con jamón de pavo y tomate", cat:"Once", e:"🍞", min:5, porc:"2 rebanadas", k:197, p:14, c:27, g:3,
   ing:["2 rebanadas de pan integral", "2 láminas de jamón de pavo", "1/2 tomate"],
   pasos:["Tuesta el pan.", "Pon el pavo y el tomate.", "Agrega orégano a gusto."] },
 { n:"Galletas de arroz con palta y huevo", cat:"Once", e:"🥚", min:10, porc:"2 galletas", k:191, p:8, c:18, g:10,
   ing:["2 galletas de arroz", "2 cucharadas de palta", "1 huevo duro", "Sal y merkén"],
   pasos:["Unta la palta en las galletas.", "Pon el huevo duro en láminas encima.", "Termina con sal y merkén."] },
 { n:"Batido de plátano con leche", cat:"Once", e:"🍌", min:3, porc:"1 vaso", k:187, p:8, c:37, g:1,
   ing:["200 ml de leche descremada", "1 plátano", "Canela"],
   pasos:["Licúa la leche con el plátano.", "Sirve con canela."] },
 { n:"Mini pizzas de pan pita", cat:"Once", e:"🍕", min:12, porc:"1 pita", k:269, p:13, c:36, g:8,
   ing:["1 pan pita integral", "2 cucharadas de salsa de tomate", "30 g de queso mozzarella", "Tomate y orégano"],
   pasos:["Unta la salsa sobre la pita.", "Agrega el queso, el tomate y el orégano.", "Hornea a 200 °C por 8 minutos."] },
 { n:"Mix de frutos secos", cat:"Colación", e:"🥜", min:1, porc:"1 puñado (25 g)", k:154, p:4, c:5, g:13,
   ing:["25 g de almendras, nueces y maní sin sal"],
   pasos:["Sirve un puñado: no más, porque son muy calóricos."] },
 { n:"Yogur griego con miel y nueces", cat:"Colación", e:"🍯", min:3, porc:"1 pote", k:180, p:16, c:12, g:7,
   ing:["150 g de yogur griego light", "1 cucharadita de miel", "10 g de nueces picadas"],
   pasos:["Sirve el yogur.", "Agrega la miel y las nueces."] },
 { n:"Quesillo con tomate y orégano", cat:"Colación", e:"🍅", min:3, porc:"1 porción", k:129, p:15, c:8, g:4,
   ing:["100 g de quesillo", "1 tomate", "Orégano y sal"],
   pasos:["Corta el quesillo y el tomate en rodajas.", "Intercala y termina con orégano."] },
 { n:"Rollitos de pavo y queso", cat:"Colación", e:"🧀", min:3, porc:"3 rollitos", k:136, p:16, c:2, g:7,
   ing:["3 láminas de jamón de pavo", "1 lámina de queso gauda", "Hojas de lechuga (opcional)"],
   pasos:["Corta el queso en 3 tiras.", "Enrolla cada tira en una lámina de pavo."] },
 { n:"Palitos de verduras con dip de yogur", cat:"Colación", e:"🥕", min:8, porc:"1 porción", k:70, p:4, c:12, g:0,
   ing:["1 taza de palitos de zanahoria y apio", "1/2 yogur natural light", "Ajo, limón y ciboulette"],
   pasos:["Mezcla el yogur con ajo, limón y ciboulette.", "Sirve con los palitos para untar."] },
 { n:"Plátano con mantequilla de maní", cat:"Colación", e:"🍌", min:2, porc:"1/2 plátano", k:109, p:2, c:15, g:4,
   ing:["1/2 plátano", "1/2 cucharada de mantequilla de maní"],
   pasos:["Corta el plátano en rodajas.", "Pon un poco de mantequilla de maní en cada una."] },
 { n:"Pera con queso fresco", cat:"Colación", e:"🍐", min:3, porc:"1 pera", k:173, p:5, c:28, g:4,
   ing:["1 pera", "30 g de queso fresco"],
   pasos:["Corta la pera en gajos.", "Acompaña con el queso fresco en cubos."] },
 { n:"Huevo duro y mandarina", cat:"Colación", e:"🥚", min:10, porc:"1 huevo + 1 fruta", k:124, p:7, c:12, g:5,
   ing:["1 huevo", "1 mandarina", "Sal"],
   pasos:["Cuece el huevo 9 minutos.", "Pélalo y cómelo con la mandarina."] },
 { n:"Galletas de arroz con quesillo", cat:"Colación", e:"🍘", min:3, porc:"2 galletas", k:120, p:8, c:16, g:2,
   ing:["2 galletas de arroz", "50 g de quesillo", "Tomate (opcional)"],
   pasos:["Pon el quesillo en láminas sobre las galletas.", "Agrega tomate si quieres."] },
 { n:"Batido de proteína con agua", cat:"Colación", e:"🥤", min:2, porc:"1 vaso", k:122, p:24, c:3, g:2,
   ing:["1 scoop de proteína whey (30 g)", "250 ml de agua fría"],
   pasos:["Pon la proteína y el agua en un shaker.", "Agita 20 segundos. Ideal después de entrenar."] },
 { n:"Leche con cacao", cat:"Colación", e:"🥛", min:3, porc:"1 vaso", k:104, p:10, c:14, g:1,
   ing:["250 ml de leche descremada", "1 cucharadita de cacao amargo", "Endulzante"],
   pasos:["Mezcla el cacao con un poco de leche hasta disolver.", "Agrega el resto de la leche y el endulzante."] },
 { n:"Uvas con almendras", cat:"Colación", e:"🍇", min:2, porc:"1 porción", k:119, p:3, c:16, g:5,
   ing:["1/2 taza de uvas", "10 g de almendras"],
   pasos:["Sirve las uvas con las almendras."] },
 { n:"Atún con galletas de agua", cat:"Colación", e:"🐟", min:5, porc:"3 galletas", k:139, p:16, c:13, g:3,
   ing:["1/2 lata de atún en agua", "3 galletas de agua", "Limón y cebollín"],
   pasos:["Mezcla el atún con limón y cebollín.", "Sírvelo sobre las galletas."] },
 { n:"Pepino con limón y merkén", cat:"Colación", e:"🥒", min:3, porc:"1 taza", k:22, p:1, c:4, g:0,
   ing:["1 pepino", "Limón, sal y merkén"],
   pasos:["Corta el pepino en bastones.", "Aliña con limón, sal y merkén. Colación muy liviana."] },
 { n:"Barrita proteica casera", cat:"Colación", e:"🍫", min:15, porc:"1 barrita", k:187, p:16, c:17, g:6,
   ing:["20 g de avena", "15 g de proteína whey", "1/2 cucharada de mantequilla de maní", "1 a 2 cucharadas de leche descremada"],
   pasos:["Mezcla todo hasta formar una masa.", "Dale forma de barrita.", "Refrigera 30 minutos."] },
 { n:"Quesillo con piña", cat:"Colación", e:"🍍", min:3, porc:"1 pote", k:150, p:14, c:14, g:4,
   ing:["100 g de quesillo", "1/2 taza de piña picada"],
   pasos:["Pica el quesillo y la piña.", "Mezcla y sirve frío."] },
 { n:"Chips de manzana al horno", cat:"Colación", e:"🍎", min:60, porc:"1 manzana", k:105, p:0, c:25, g:0,
   ing:["1 manzana", "Canela"],
   pasos:["Corta la manzana en láminas muy delgadas.", "Ponlas en una bandeja con papel y espolvorea canela.", "Hornea a 100 °C por 1 hora, dando vuelta a la mitad, hasta que estén crocantes."] },
 { n:"Smoothie verde de kiwi", cat:"Colación", e:"🥝", min:3, porc:"1 vaso", k:112, p:7, c:19, g:1,
   ing:["1 kiwi", "1/2 taza de espinaca", "1 yogur natural light", "Hielo"],
   pasos:["Licúa todo hasta que quede liso.", "Sirve frío."] },
 { n:"Maní tostado sin sal", cat:"Colación", e:"🥜", min:1, porc:"1 puñado (28 g)", k:178, p:7, c:6, g:14,
   ing:["28 g de maní tostado sin sal"],
   pasos:["Sirve un puñado medido."] },
 { n:"Palitos de queso y aceitunas", cat:"Colación", e:"🫒", min:3, porc:"1 porción", k:120, p:7, c:2, g:10,
   ing:["30 g de queso mozzarella en bastones", "5 aceitunas"],
   pasos:["Corta el queso en bastones.", "Sirve con las aceitunas."] },
 /* Más cenas (10-10-2026, pedido de la dueña). */
 { n:"Pechuga a la plancha con ensalada verde", cat:"Cena", e:"🥗", min:15, porc:"1 plato", k:272, p:42, c:5, g:10,
   ing:["130 g de pechuga de pollo", "Lechuga, pepino y apio", "1 cucharadita de aceite de oliva", "Limón, ajo y sal"],
   pasos:["Condimenta el pollo y cocínalo a la plancha 5 a 6 minutos por lado.", "Pica las verduras para la ensalada.", "Aliña con aceite, limón y sal.", "Sirve el pollo en tiras sobre la ensalada."] },
 { n:"Reineta al horno con verduras asadas", cat:"Cena", e:"🐟", min:30, porc:"1 plato", k:260, p:33, c:15, g:8,
   ing:["150 g de reineta", "1 1/2 taza de zapallo italiano, pimentón y cebolla", "1 cucharadita de aceite", "Limón, orégano y sal"],
   pasos:["Precalienta el horno a 200 °C.", "Pon las verduras en una bandeja con el aceite y hornea 10 minutos.", "Agrega el pescado condimentado y hornea 12 minutos más."] },
 { n:"Crema de zapallo con semillas", cat:"Cena", e:"🎃", min:30, porc:"1 plato", k:186, p:8, c:26, g:5,
   ing:["1 1/2 taza de zapallo", "1/4 de cebolla", "100 ml de leche descremada", "10 g de semillas de zapallo", "Sal y nuez moscada"],
   pasos:["Cuece el zapallo y la cebolla en poca agua hasta que estén blandos.", "Licúa con la leche, la sal y la nuez moscada.", "Sirve caliente con las semillas encima."] },
 { n:"Crema de brócoli con quesillo", cat:"Cena", e:"🥦", min:30, porc:"1 plato", k:217, p:17, c:30, g:3,
   ing:["1 1/2 taza de brócoli", "1/4 de papa", "100 ml de leche descremada", "50 g de quesillo", "Ajo y sal"],
   pasos:["Cuece el brócoli y la papa con ajo en poca agua.", "Licúa con la leche y la sal.", "Sirve con el quesillo en cubos encima."] },
 { n:"Ensalada tibia de quínoa y pollo", cat:"Cena", e:"🥙", min:20, porc:"1 plato", k:337, p:36, c:26, g:10,
   ing:["1/2 taza de quínoa cocida", "100 g de pollo a la plancha", "Tomate y pepino picados", "1 cucharadita de aceite de oliva", "Limón, menta y sal"],
   pasos:["Cuece la quínoa y déjala tibia.", "Cocina el pollo y córtalo en cubos.", "Mezcla todo con las verduras.", "Aliña con aceite, limón, menta y sal."] },
 { n:"Omelette de verduras", cat:"Cena", e:"🍳", min:12, porc:"1 omelette", k:196, p:18, c:9, g:10,
   ing:["2 huevos y 1 clara", "1 taza de pimentón, cebolla y tomate picados", "Sal, pimienta y orégano"],
   pasos:["Saltea las verduras 3 minutos en un sartén antiadherente.", "Agrega los huevos batidos.", "Cocina a fuego bajo, dobla y sirve."] },
 { n:"Salmón con espárragos", cat:"Cena", e:"🍣", min:20, porc:"1 plato", k:271, p:29, c:4, g:15,
   ing:["120 g de salmón", "6 espárragos", "Limón, ajo, sal y pimienta"],
   pasos:["Condimenta el salmón con limón, ajo, sal y pimienta.", "Cocínalo en un sartén antiadherente 4 minutos por lado.", "Saltea o cuece al vapor los espárragos 4 minutos.", "Sirve con limón."] },
 { n:"Pollo al curry con arroz integral", cat:"Cena", e:"🍛", min:25, porc:"1 plato", k:385, p:43, c:30, g:10,
   ing:["120 g de pollo en cubos", "1 taza de zapallo italiano picado", "1/2 taza de arroz integral cocido", "50 ml de leche descremada", "1 cucharadita de aceite y 1 cucharadita de curry"],
   pasos:["Dora el pollo con el aceite.", "Agrega el zapallo italiano y el curry, y saltea 3 minutos.", "Suma la leche y cocina 5 minutos hasta que espese.", "Sirve con el arroz."] },
 { n:"Brochetas de pollo y verduras", cat:"Cena", e:"🍢", min:25, porc:"2 brochetas", k:278, p:39, c:10, g:9,
   ing:["120 g de pollo en cubos", "Pimentón, cebolla y zapallo italiano en trozos", "1 cucharadita de aceite", "Merkén, ajo y sal"],
   pasos:["Arma las brochetas intercalando pollo y verduras.", "Píntalas con el aceite y los condimentos.", "Cocínalas a la plancha o al horno 15 minutos, dando vuelta."] },
 { n:"Albóndigas de pavo en salsa de tomate", cat:"Cena", e:"🍝", min:30, porc:"5 albóndigas", k:270, p:32, c:15, g:9,
   ing:["120 g de pavo molido", "10 g de avena", "1 clara", "1/2 taza de salsa de tomate casera", "Ajo, perejil y sal"],
   pasos:["Mezcla el pavo con la avena, la clara, el ajo, el perejil y la sal.", "Forma 5 albóndigas y dóralas en un sartén antiadherente.", "Agrega la salsa de tomate y cocina 12 minutos tapado."] },
 { n:"Lasaña de zapallo italiano", cat:"Cena", e:"🥒", min:40, porc:"1 porción", k:329, p:34, c:16, g:14,
   ing:["1 zapallo italiano grande en láminas", "90 g de carne molida magra", "1/2 taza de salsa de tomate", "50 g de quesillo", "Orégano y sal"],
   pasos:["Dora la carne con la salsa de tomate y el orégano.", "En un molde, intercala láminas de zapallo, carne y quesillo.", "Hornea a 180 °C por 25 minutos."] },
 { n:"Ensalada de pollo, palta y huevo", cat:"Cena", e:"🥑", min:15, porc:"1 plato grande", k:320, p:39, c:9, g:14,
   ing:["100 g de pollo cocido", "1/4 de palta", "1 huevo duro", "Lechuga y tomate", "Limón y sal"],
   pasos:["Pica el pollo, la palta, el huevo y las verduras.", "Mezcla todo en un bowl.", "Aliña con limón y sal."] },
 { n:"Tortilla de papas al horno", cat:"Cena", e:"🥔", min:35, porc:"1 porción", k:299, p:20, c:33, g:10,
   ing:["1 papa mediana en láminas finas", "2 huevos y 1 clara", "1/4 de cebolla", "Sal y pimienta"],
   pasos:["Cuece las láminas de papa 5 minutos.", "Mézclalas con los huevos batidos y la cebolla.", "Vierte en un molde chico y hornea a 180 °C por 20 minutos."] },
 { n:"Sopa de lentejas con espinaca", cat:"Cena", e:"🍲", min:30, porc:"1 plato hondo", k:284, p:17, c:41, g:6,
   ing:["3/4 taza de lentejas cocidas", "1/2 taza de espinaca", "Zanahoria y cebolla picadas", "1 cucharadita de aceite", "Comino y sal"],
   pasos:["Sofríe la cebolla y la zanahoria en el aceite.", "Agrega las lentejas, 2 tazas de agua y el comino.", "Cocina 15 minutos y suma la espinaca al final."] },
 { n:"Pescado al papillote con limón", cat:"Cena", e:"🍋", min:25, porc:"1 porción", k:224, p:32, c:8, g:7,
   ing:["150 g de merluza", "1 taza de verduras en tiras (zanahoria, zapallo italiano, cebolla)", "1 cucharadita de aceite", "Limón, eneldo y sal"],
   pasos:["Precalienta el horno a 200 °C.", "Pon las verduras y el pescado sobre papel de aluminio, con limón, eneldo, sal y el aceite.", "Cierra bien el paquete y hornea 18 minutos."] },
 { n:"Fajitas de pollo en hojas de lechuga", cat:"Cena", e:"🌮", min:20, porc:"4 fajitas", k:328, p:39, c:13, g:14,
   ing:["120 g de pollo en tiras", "1 taza de pimentón y cebolla en tiras", "2 cucharadas de palta", "4 hojas grandes de lechuga", "1 cucharadita de aceite, comino y sal"],
   pasos:["Saltea el pollo con el aceite y el comino.", "Agrega el pimentón y la cebolla y cocina 4 minutos.", "Rellena las hojas de lechuga y pon la palta encima."] },
 { n:"Huevos al horno con tomate y espinaca", cat:"Cena", e:"🍅", min:20, porc:"2 huevos + 1 pan", k:265, p:19, c:22, g:11,
   ing:["2 huevos", "1/2 taza de salsa de tomate", "1/2 taza de espinaca", "1 rebanada de pan integral", "Comino, sal y pimienta"],
   pasos:["Calienta la salsa de tomate con la espinaca y el comino en un sartén.", "Haz dos huecos y rompe un huevo en cada uno.", "Tapa y cocina 6 a 8 minutos a fuego bajo.", "Sirve con el pan tostado."] },
 { n:"Pavo al horno con puré de coliflor", cat:"Cena", e:"🦃", min:40, porc:"1 plato", k:278, p:50, c:9, g:5,
   ing:["150 g de pechuga de pavo", "1 1/2 taza de coliflor cocida", "50 ml de leche descremada", "1/2 cucharadita de aceite", "Ajo, romero y sal"],
   pasos:["Condimenta el pavo con ajo, romero, sal y el aceite.", "Hornéalo a 190 °C por 30 minutos.", "Muele la coliflor con la leche y la sal para el puré.", "Sirve el pavo en láminas sobre el puré."] },
 { n:"Ensalada de atún, huevo y porotos verdes", cat:"Cena", e:"🥗", min:20, porc:"1 plato grande", k:362, p:40, c:26, g:11,
   ing:["1 lata de atún en agua", "1 huevo duro", "1/2 taza de porotos verdes", "1/2 papa cocida", "Lechuga y tomate", "1 cucharadita de aceite de oliva y limón"],
   pasos:["Cuece los porotos verdes y la papa.", "Arma el plato con la lechuga, el tomate, la papa, los porotos, el atún y el huevo.", "Aliña con aceite, limón y sal."] },
 { n:"Camarones salteados con zapallo italiano", cat:"Cena", e:"🍤", min:15, porc:"1 plato", k:210, p:32, c:8, g:6,
   ing:["120 g de camarones", "1 1/2 taza de zapallo italiano en tiras", "1 cucharadita de aceite", "Ajo, limón, perejil y sal"],
   pasos:["Saltea el ajo en el aceite.", "Agrega los camarones y cocina 2 minutos por lado.", "Suma el zapallo italiano y saltea 3 minutos.", "Termina con limón y perejil."] }
];
